import assert from 'node:assert/strict';
import {readFileSync,writeFileSync} from 'node:fs';
import {pathToFileURL} from 'node:url';
import {join} from 'node:path';
const [agentRoot,runtimePath,corpusPath,outputPath,emitterPath,boundaryCommit]=process.argv.slice(2);
if(!agentRoot||!runtimePath||!corpusPath||!outputPath||!emitterPath||!boundaryCommit||!/^[0-9a-f]{40}$/.test(boundaryCommit))throw Error('Expected Agent root, runtime, fixture corpus and output paths');
const {verifyRuntime,sha256}=await import(pathToFileURL(join(agentRoot,'tools/agent4/dependencies.mjs')));
const runtime=verifyRuntime(runtimePath);
const world=await import(pathToFileURL(runtime.entrypoint)),kernelBytes=readFileSync(runtime.kernelPath);
const {wasmtime}=await import(pathToFileURL(join(agentRoot,"test/agent4/independent/execute.mjs")));
const words=values=>{const b=Buffer.alloc(values.length*8);values.forEach((v,i)=>b.writeBigUInt64LE(BigInt(v),i*8));return b;};
const max=(1n<<64n)-1n;
const cases=[];
for(const name of ['rotating','parallel','product']) cases.push([name,[false,true].map(flag=>[Buffer.concat([words([1,2,4,8]),Buffer.from([+flag])]),words([flag?6:3])])]);
cases.push(['modes',[0,9,max].map(u=>[Buffer.concat([words([1,2,4,u]),Buffer.from([1])]),words([u===0?6:3])])]);
cases.push(['recurrent',[0,1,2,3,8,31].map(count=>{let p=1n,q=2n,r=4n;for(let i=0;i<count;i++)[p,q,r]=[q,r,p^8n^0xa5n];return[Buffer.concat([words([1,2,4,8]),Buffer.from([count])]),words([p^q^8n^0xa5n])];})]);
for(const n of[2,3,8,32,64,128]){const values=Array.from({length:n},(_,i)=>BigInt(i+1)),parity=values.reduce((a,b)=>a^b,0n);for(const suffix of ['', '-direct'])cases.push(['parity-'+n+suffix,[false,true].map(flag=>[Buffer.concat([words([...values,0xa5]),Buffer.from([+flag])]),words([parity^(flag?0xa5n:0n)])])]);}
for(const n of [8,32,64,128]){const values=Array.from({length:n},(_,i)=>BigInt(i+1)),parity=values.reduce((a,b)=>a^b,0n);cases.push(['parameters-'+n,[false,true].map(flag=>[Buffer.concat([words([...values,0xa5]),Buffer.from([+flag])]),words([parity^(flag?0xa5n:0n)])])]);}
const fresh=async()=>{const k=await world.Kernel.create({bytes:kernelBytes,expectedSha256:runtime.kernelSha256});k.setLimits({input:256<<20,working:256<<20,output:256<<20});return k;};
const rows=[];
for(const [name,inputs] of cases){const images=Object.fromEntries(['structural','semantic'].map(arm=>[arm,readFileSync(join(corpusPath,`${name}-${arm}.bpi3`))]));let executions=0,rejections=0;if(name==='parameters-8'||name==='parameters-32')assert(images.semantic.length<images.structural.length,'direct parameter opportunity must be selected');
 for(const arm of ['structural','semantic']){for(const [initialArgs,expected] of inputs){const k=await fresh(),out=world.decodeOutcome(k.invoke(world.encodeInput({image:images[arm],initialArgs})));assert.equal(out.kind,'completed',name);assert.deepEqual(Buffer.from(out.value),expected,name);const command=world.encodeInput({image:images[arm],initialArgs});const inputPath=join(corpusPath,`${name}-${arm}-${executions}.pki3`);writeFileSync(inputPath,command);const independent=wasmtime(runtime,inputPath);assert.equal(independent.status,0,independent.stderr.toString());assert.deepEqual(independent.stdout,Buffer.from(k.invoke(command)),name+' Wasmtime');executions++;}const k=await fresh();assert.throws(()=>k.invoke(world.encodeInput({image:images[arm],initialArgs:inputs[0][0].subarray(1)})),{code:'WORLD_KERNEL_REJECTED'});rejections++;}
 const k=await fresh(),other=await fresh(),a=k.prepare(images.structural),b=other.prepare(images.semantic),s=k.start(a,inputs[0][0]);const out=world.decodeOutcome(k.drive(s,{quantum:1,checkpoint:true}));assert.equal(out.kind,'progressed',name);const state=k.checkpoint(s,{transfer:true});let wrongImageRejected=false;if(sha256(images.structural)!==sha256(images.semantic)){assert.throws(()=>other.restore(b,state),{code:'WORLD_KERNEL_REJECTED'});wrongImageRejected=true;}const resumed=k.restore(a,state);const replay=world.decodeOutcome(k.drive(resumed,{}));assert.equal(replay.kind,"completed",name);assert.deepEqual(Buffer.from(replay.value),inputs[0][1],name);k.close(resumed);k.releasePrepared(a);other.releasePrepared(b);assert.equal(other.usage().workingLive,0n,name);assert.equal(k.usage().workingLive,0n,name);
 rows.push({name,images:Object.fromEntries(Object.entries(images).map(([key,v])=>[key,{bytes:v.length,sha256:sha256(v)}])),executions,wasmtimeAgreements:executions,malformedInputsRejected:rejections,sameImageRestore:true,wrongImageRejected});
}
const report={scope:'Admitted-record shared closed-compiler pairs, plus explicitly labelled parity-direct standalone checked affine pairs; unchanged authenticated production Node/WASM and independent Wasmtime; independent explicit value oracles and portable-State binding checks',boundary:boundaryCommit,kernelSha256:runtime.kernelSha256,emitterSha256:sha256(readFileSync(emitterPath)),runnerSha256:sha256(readFileSync(new URL(import.meta.url))),rows};writeFileSync(outputPath,JSON.stringify(report,null,2)+'\n');console.log(JSON.stringify({cases:rows.length,executions:rows.reduce((n,r)=>n+r.executions,0),malformedInputsRejected:rows.reduce((n,r)=>n+r.malformedInputsRejected,0),sameImageRestores:rows.length,wrongImageRejections:rows.filter(r=>r.wrongImageRejected).length}));
