// Same-contract predecessor/candidate economics for the selected repeated-callable witness.
import assert from 'node:assert/strict';
import {readFileSync,writeFileSync} from 'node:fs';
import {execFileSync} from 'node:child_process';
import {pathToFileURL} from 'node:url';
import {join,basename} from 'node:path';
import {createHash} from 'node:crypto';
import os from 'node:os';
const hash=b=>createHash('sha256').update(b).digest('hex');
const median=a=>[...a].sort((x,y)=>x-y)[Math.floor(a.length/2)];
async function load(agent,runtime){const {verifyRuntime}=await import(pathToFileURL(join(agent,'tools/agent4/dependencies.mjs')));const identity=verifyRuntime(runtime),world=await import(pathToFileURL(identity.entrypoint));return{identity,world};}
async function fresh(world,identity){const k=await world.Kernel.create({bytes:readFileSync(identity.kernelPath),expectedSha256:identity.kernelSha256});k.setLimits({input:256<<20,working:256<<20,output:256<<20});return k;}
const args=process.argv.slice(2);
if(args[0]==='--sample'){
 const [,agent,runtime,imagePath,argumentsHex,phase,expected]=args;assert(['admission','fresh','cycle'].includes(phase));
 const {identity,world}=await load(agent,runtime),k=await fresh(world,identity),image=readFileSync(imagePath),initialArgs=Buffer.from(argumentsHex,'hex');
 const input=world.encodeInput({image,initialArgs,...(phase==='cycle'?{quantum:1n}:{})}),samplesNs=[];
 for(let window=0;window<12;window++){let total=0;const batch=phase==='cycle'?1:64;for(let n=0;n<batch;n++){
  const begin=process.hrtime.bigint();
  if(phase==='admission'){const p=k.prepare(image);total+=Number(process.hrtime.bigint()-begin);k.releasePrepared(p);}
  else{let output=k.invoke(input);if(phase==='cycle'){let state=world.decodeOutcome(output),steps=1;while(state.kind==='progressed'){assert(++steps<100);output=k.invoke(world.encodeInput({image,state:state.state,quantum:1n}));state=world.decodeOutcome(output);}assert.equal(state.kind,'completed');}total+=Number(process.hrtime.bigint()-begin);assert.equal(hash(output),expected);}
  assert.equal(k.usage().workingLive,0n);
 }if(window>=3)samplesNs.push(total/batch);}
 console.log(JSON.stringify({samplesNs}));
}else{
 const [agent,runtime,controlDirectory,candidateDirectory,output,admission,freshNative,cycleNative,memoryNative,mode,controlSource]=args;assert(args.length>=9&&args.length<=11);if(controlSource)assert(/^[0-9a-f]{40}$/.test(controlSource));const variants=mode==='variants',constants=mode==='constants'||mode==='outline'||mode==='packing',wordMode=mode==='words'||mode==='tails'||mode==='duplicate',joins=mode==='joins'||mode==='recursive',recursive=mode==='recursive';const captures=mode==='captures';assert(!mode||variants||constants||wordMode||joins||captures);
 const {identity,world}=await load(agent,runtime),kernel=await fresh(world,identity),arms={control:join(controlDirectory,mode==='packing'?'packing-shared-semantic.bpi3':captures?'capture-shared-semantic.bpi3':mode==='outline'?'outline-shared-semantic.bpi3':mode==='duplicate'?'duplicate-shared-semantic.bpi3':mode==='tails'?'tails-shared-semantic.bpi3':recursive?'recursive-shared-semantic.bpi3':joins?'join-shared-semantic.bpi3':wordMode?'word-shared-semantic.bpi3':constants?'constant-shared-semantic.bpi3':variants?'variant-total-shared-semantic.bpi3':'callable-shared-semantic.bpi3'),candidate:join(candidateDirectory,mode==='packing'?'packing-shared-semantic.bpi3':captures?'capture-shared-semantic.bpi3':mode==='outline'?'outline-shared-semantic.bpi3':mode==='duplicate'?'duplicate-shared-semantic.bpi3':mode==='tails'?'tails-shared-semantic.bpi3':recursive?'recursive-shared-semantic.bpi3':joins?'join-shared-semantic.bpi3':wordMode?'word-shared-semantic.bpi3':constants?'constant-shared-semantic.bpi3':variants?'variant-total-shared-semantic.bpi3':'callable-shared-semantic.bpi3')};
 const imageHashes=Object.fromEntries(Object.entries(arms).map(([arm,path])=>[arm,hash(readFileSync(path))]));assert.notEqual(imageHashes.control,imageHashes.candidate);
 const mix=value=>{for(let i=0;i<24;i++){if(i%3===0)value^=0x9e3779b97f4a7c15n;else if(i%3===1)value=~value;else value|=0x9e3779b97f4a7c15n;}return BigInt.asUintN(64,value);};
 const fixtures=mode==='packing'?[['identity-first',7n,11n,true,false,[BigInt.asUintN(64,~11n),BigInt.asUintN(64,~7n)]],['identity-second',7n,11n,false,false,[BigInt.asUintN(64,~7n),BigInt.asUintN(64,~11n)]]]:captures?[['identity-first',7n,11n,true,false,8n],['identity-second',7n,11n,false,true,4n],['third',7n,11n,false,false,BigInt.asUintN(64,(~7n)|(~11n))]]:mode==='outline'?[['identity-first',7n,11n,true,false,mix(7n)],['identity-second',7n,11n,false,false,mix(11n)]]:mode==='duplicate'?[['identity-first',7n,0n,true,false,BigInt.asUintN(64,~7n)],['identity-second',7n,0n,false,false,7n]]:mode==='tails'?[['identity-first',7n,0n,true,false,BigInt.asUintN(64,~7n)],['identity-second',7n,0n,false,false,BigInt.asUintN(64,~7n)]]:joins?[['identity-first',7n,11n,true,false,[7n,11n]],['swap-first',7n,11n,true,true,[11n,7n]],['identity-second',7n,11n,false,false,[11n,7n]],['swap-second',7n,11n,false,true,recursive?[11n,7n]:[7n,11n]]]:wordMode?[['identity-first',7n,0n,true,false,7n],['identity-second',7n,0n,false,false,BigInt.asUintN(64,~7n)]]:constants?[['identity-first',7n,11n,true,false,7n],['identity-second',7n,11n,false,false,11n]]:variants?[['identity-first',7n,11n,true,false,7n],['identity-second',7n,11n,false,true,11n],['third',7n,11n,false,false,7n]]:[['identity-first',7n,11n,true,false,15n],['identity-second',7n,11n,false,true,15n],['complement',7n,11n,false,false,BigInt.asUintN(64,(~7n)|(~11n))]];
 const inputs={};
 for(const [name,x,y,first,second,expected]of fixtures){const bytes=Buffer.alloc(wordMode?9:constants?17:18);bytes.writeBigUInt64LE(x);if(wordMode){bytes[8]=+first;}else{bytes.writeBigUInt64LE(y,8);bytes[16]=+first;if(!constants)bytes[17]=+second;}inputs[name]={argumentsHex:bytes.toString('hex'),arms:{}};for(const [arm,path]of Object.entries(arms)){const image=readFileSync(path),encoded=world.encodeInput({image,initialArgs:bytes}),result=kernel.invoke(encoded),decoded=world.decodeOutcome(result);assert.equal(decoded.kind,'completed');assert.deepEqual(Buffer.from(decoded.value),Buffer.concat((Array.isArray(expected)?expected:[expected]).map(value=>Buffer.from(Uint8Array.from({length:8},(_,i)=>Number((value>>BigInt(i*8))&255n))))));const pki=join(candidateDirectory,`timing-${name}-${arm}.pki3`);writeFileSync(pki,encoded);inputs[name].arms[arm]={path,pki,expected:hash(result),inputSha256:hash(encoded)};}}
 const memory={};
 for(const [arm,path]of Object.entries(arms)){const image=readFileSync(path),native=JSON.parse(execFileSync(memoryNative,[path],{encoding:'utf8'})),k=await fresh(world,identity),p=k.prepare(image),usage=k.usage();memory[arm]={native,wasmAdmission:{peak:Number(usage.workingPeak),retained:Number(usage.workingLive),capacity:usage.memoryBytes}};k.releasePrepared(p);assert.equal(k.usage().workingLive,0n);}
 const executables={admission,fresh:freshNative,cycle:cycleNative};
 const report={status:'running',scope:`Selected ${mode??'callable'} fixture; exact images and tool hashes below. Complete cycle includes quantum-one checkpoint/restore.`,controlSource:controlSource??null,environment:{platform:process.platform,arch:process.arch,os:os.release(),cpu:os.cpus()[0].model,node:process.version},kernelSha256:identity.kernelSha256,imageHashes,executables:Object.fromEntries(Object.entries({...executables,memory:memoryNative}).map(([key,path])=>[key,{file:basename(path),sha256:hash(readFileSync(path))}])),memory,protocol:'Three alternating windows; three warmups/nine samples; two extra windows if an initial median ratio exceeds 1.05. No exclusive-host claim.',cells:[]};
 for(const engine of ['native','wasm'])for(const phase of ['admission','fresh','cycle'])for(const [name,input]of Object.entries(inputs)){
  if(phase==='admission'&&name!=='identity-first')continue;
  const windows=[];for(let window=0;window<5;window++){if(window===3&&!windows.some(w=>w.ratio>1.05))break;const order=window%2?['candidate','control']:['control','candidate'],results={};for(const arm of order){const item=input.arms[arm];let command,argv,options={encoding:'utf8',timeout:120000};if(engine==='wasm'){command=process.execPath;argv=[new URL(import.meta.url).pathname,'--sample',agent,runtime,item.path,input.argumentsHex,phase,item.expected];}else{command=executables[phase];argv=phase==='admission'?[item.path]:phase==='cycle'?[item.pki,item.expected]:[item.expected];if(phase==='fresh')options.input=readFileSync(item.pki);}results[arm]=JSON.parse(execFileSync(command,argv,options));}windows.push({order,control:results.control,candidate:results.candidate,ratio:median(results.candidate.samplesNs)/median(results.control.samplesNs)});}
  const ratio=median(windows.map(w=>w.ratio));report.cells.push({engine,phase,path:name,windows,medianRatio:ratio,pairedMedianDeltaNs:median(windows.map(w=>median(w.candidate.samplesNs)-median(w.control.samplesNs))),confirmedSlowdown:windows.length===5&&ratio>1.05&&windows.filter(w=>w.ratio>1.05).length>=4});writeFileSync(output,JSON.stringify(report,null,2)+'\n');
 }
 report.status='complete';writeFileSync(output,JSON.stringify(report,null,2)+'\n');console.log(JSON.stringify({cells:report.cells.length,memory,confirmed:report.cells.filter(c=>c.confirmedSlowdown).map(({engine,phase,path,medianRatio,pairedMedianDeltaNs})=>({engine,phase,path,medianRatio,pairedMedianDeltaNs}))}));
}
