#ifdef __APPLE__
#define GSYM(x) _##x
#else
#define GSYM(x) x
#endif

.text
.globl GSYM(shift_swap_context)
.p2align 2
GSYM(shift_swap_context):
    mov x9, sp
    str x9, [x0, #0]
    stp x19, x20, [x0, #8]
    stp x21, x22, [x0, #24]
    stp x23, x24, [x0, #40]
    stp x25, x26, [x0, #56]
    stp x27, x28, [x0, #72]
    stp x29, x30, [x0, #88]

    ldr x9, [x1, #0]
    mov sp, x9
    ldp x19, x20, [x1, #8]
    ldp x21, x22, [x1, #24]
    ldp x23, x24, [x1, #40]
    ldp x25, x26, [x1, #56]
    ldp x27, x28, [x1, #72]
    ldp x29, x30, [x1, #88]
    ret
