#!/usr/bin/env sh
set -eu

repo_root="$(CDPATH= cd -- "$(dirname "$0")/../.." && pwd)"
contract="$repo_root/docs/source_lowering_contract.md"

[ -f "$contract" ] || {
  echo "missing source-lowering contract" >&2
  exit 1
}

grep -q '^# Source Lowering Contract$' "$contract"
grep -q '^## Status$' "$contract"
grep -q '^## Public Boundary$' "$contract"
grep -q '^## Preserved Semantic Invariants$' "$contract"
grep -q '^## Source Corpus$' "$contract"
grep -q '^## Structural Exclusions$' "$contract"
grep -q '^## Covered Rows$' "$contract"
grep -q '^## Coverage Matrix$' "$contract"
grep -q '^## Proof Surface$' "$contract"
grep -q 'internal source-lowering contract' "$contract"
grep -q 'shift.Program(.{ ... }, Body)' "$contract"
grep -q 'shift.run(&runtime, Program, bindings)' "$contract"
grep -q 'shift.Decl.\*' "$contract"
grep -q 'shift.Ops.\*' "$contract"
! grep -q 'shift\.decl' "$contract"
! grep -q 'shift\.ops' "$contract"
grep -q 'shift-source-lower' "$contract"
grep -q 'static delimitation' "$contract"
grep -q 'one-shot linearity' "$contract"
grep -q 'source.local_mutation_resume' "$contract"
grep -q 'source.branch_resume' "$contract"
grep -q 'source.loop_resume' "$contract"
grep -q 'source.helper_call_resume' "$contract"
grep -q 'source.nested_prompt_static_redelim' "$contract"
grep -q 'source.typed_error_try' "$contract"
grep -q 'source.defer_resume' "$contract"
grep -q 'source.errdefer_error' "$contract"
grep -q 'example.early_exit' "$contract"
grep -q 'example.resume_or_return' "$contract"
grep -q 'example.front_door_workflow' "$contract"
grep -q 'example.nested_workflow' "$contract"
grep -q 'example.define_basic' "$contract"
grep -q 'example.define_choice_basic' "$contract"
grep -q 'example.define_abort_basic' "$contract"
grep -q 'example.resource_basic' "$contract"
grep -q 'example.writer_basic' "$contract"
grep -q 'example.algebraic_abortive_validation' "$contract"
grep -q 'example.algebraic_artifact_search' "$contract"
grep -q 'built_in.state' "$contract"
grep -q 'built_in.reader' "$contract"
grep -q 'built_in.optional' "$contract"
grep -q 'built_in.exception' "$contract"
grep -q 'built_in.resource' "$contract"
grep -q 'built_in.writer' "$contract"
grep -q 'user_defined.transform' "$contract"
grep -q 'user_defined.choice' "$contract"
grep -q 'user_defined.abort' "$contract"
grep -q 'No public continuation handle' "$contract"
grep -q 'No runtime2' "$contract"
grep -q 'No recursion' "$contract"
grep -q 'No dynamic callee lowering' "$contract"
grep -q 'No arbitrary cross-module lowering' "$contract"
grep -q 'No reflective raw-body lowering API' "$contract"
grep -q 'No stable non-experimental runtime-call lowering API' "$contract"
grep -q 'No performance contract' "$contract"
grep -q 'docs/source_lowering_matrix.json' "$contract"
grep -q 'docs/source_lowering_coverage_matrix.json' "$contract"
grep -q 'coverage_status' "$contract"
grep -q 'zig build source-lowering-gauntlet' "$contract"
grep -q 'zig build source-lowering-coverage-check' "$contract"
grep -q 'zig build test' "$contract"
! rg -n 'shift\.decl|shift\.ops' "$repo_root/src/source_lowering.zig" >/dev/null
rg -n 'shift\.Decl|shift\.Op' "$repo_root/src/source_lowering.zig" >/dev/null
