#!/usr/bin/env sh
set -eu

repo_root="$(CDPATH= cd -- "$(dirname "$0")/../.." && pwd)"
contract="$repo_root/docs/source_lowering_contract.md"

[ -f "$contract" ] || {
  echo "missing source-lowering contract" >&2
  exit 1
}

grep -q '^# Source Lowering Contract$' "$contract"
grep -q '^## Status$' "$contract"
grep -q '^## Public Boundary$' "$contract"
grep -q '^## Preserved Semantic Invariants$' "$contract"
grep -q '^## Source Corpus$' "$contract"
grep -q '^## Structural Exclusions$' "$contract"
grep -q '^## Covered Rows$' "$contract"
grep -q '^## Coverage Matrix$' "$contract"
grep -q '^## Proof Surface$' "$contract"
grep -q 'internal source-lowering contract' "$contract"
grep -q 'shift.Row(.{ ... })' "$contract"
grep -q 'shift.effects.\*' "$contract"
grep -q 'shift.handlers.\*' "$contract"
grep -q 'shift.Decision' "$contract"
grep -q 'shift-source-lower' "$contract"
grep -q 'static delimitation' "$contract"
grep -q 'one-shot linearity' "$contract"
grep -q 'source.local_mutation_resume' "$contract"
grep -q 'source.branch_resume' "$contract"
grep -q 'source.loop_resume' "$contract"
grep -q 'source.helper_call_resume' "$contract"
grep -q 'source.nested_prompt_static_redelim' "$contract"
grep -q 'source.typed_error_try' "$contract"
grep -q 'source.defer_resume' "$contract"
grep -q 'source.errdefer_error' "$contract"
grep -q 'example.early_exit' "$contract"
grep -q 'example.resume_or_return' "$contract"
grep -q 'example.nested_workflow' "$contract"
grep -q 'example.resource_basic' "$contract"
grep -q 'example.writer_basic' "$contract"
grep -q 'open_row_state_writer' "$contract"
grep -q 'No public continuation handle' "$contract"
grep -q 'No runtime2' "$contract"
grep -q 'No recursion' "$contract"
grep -q 'No dynamic callee lowering' "$contract"
grep -q 'No arbitrary cross-module lowering' "$contract"
grep -q 'No reflective raw-body lowering API' "$contract"
grep -q 'No stable non-experimental runtime-call lowering API' "$contract"
grep -q 'No performance contract' "$contract"
grep -q 'docs/source_lowering_matrix.json' "$contract"
grep -q 'docs/source_lowering_coverage_matrix.json' "$contract"
grep -q 'coverage_status' "$contract"
grep -q 'zig build source-lowering-gauntlet' "$contract"
grep -q 'zig build source-lowering-coverage-check' "$contract"
grep -q 'zig build lowering-equivalence-report-check' "$contract"
grep -q 'zig build lowering-rejection-report-check' "$contract"
grep -q 'zig build test' "$contract"
grep -q 'open_row_state_writer' "$repo_root/test/example_proof_suite.zig"
