#!/usr/bin/env sh
set -eu

repo_root="$(CDPATH= cd -- "$(dirname "$0")/../.." && pwd)"
contract="$repo_root/docs/source_lowering_contract.md"
build_file="$repo_root/build.zig"

[ -f "$contract" ] || {
  echo "missing source-lowering contract" >&2
  exit 1
}

grep -q '^# Source Lowering Contract$' "$contract"
grep -q '^## Status$' "$contract"
grep -q '^## Public Boundary$' "$contract"
grep -q '^## Preserved Semantic Invariants$' "$contract"
grep -q '^## Source Corpus$' "$contract"
grep -q '^## Structural Exclusions$' "$contract"
grep -q '^## Covered Rows$' "$contract"
grep -q '^## Coverage Matrix$' "$contract"
grep -q '^## Proof Surface$' "$contract"
grep -q 'internal source-lowering contract' "$contract"
grep -q 'effects-library surface' "$contract"
grep -q 'lexical authoring through `shift.with(...)`' "$contract"
grep -q 'built-in and custom families through `shift.effect.*`' "$contract"
grep -q 'structural row vocabulary through `shift.ir`' "$contract"
grep -q 'explicit `shift.Runtime` ownership beneath those public lanes' "$contract"
grep -q '`shift.Program(...)`, `shift.Decl`, `shift.Op`, `shift.Decision(...)`, and' "$contract"
grep -q '`shift.run(...)` as supported compatibility surfaces' "$contract"
grep -q 'source-lowering toolchain remains restricted internal proof scaffolding' "$contract"
grep -q 'shift-source-lower' "$contract"
grep -q 'static delimitation' "$contract"
grep -q 'one-shot linearity' "$contract"
grep -q 'internal typed prompt discipline' "$contract"
grep -q 'current answer-type discipline' "$contract"
grep -q 'source.local_mutation_resume' "$contract"
grep -q 'source.branch_resume' "$contract"
grep -q 'source.loop_resume' "$contract"
grep -q 'source.helper_call_resume' "$contract"
grep -q 'source.nested_prompt_static_redelim' "$contract"
grep -q 'source.typed_error_try' "$contract"
grep -q 'source.defer_resume' "$contract"
grep -q 'source.errdefer_error' "$contract"
grep -q 'example.early_exit' "$contract"
grep -q 'example.resume_or_return' "$contract"
grep -q 'example.nested_workflow' "$contract"
grep -q 'example.resource_basic' "$contract"
grep -q 'example.writer_basic' "$contract"
grep -q 'open_row_state_writer' "$contract"
grep -q 'not an admitted source-lowering row' "$contract"
grep -q 'No public continuation handle' "$contract"
grep -q 'No runtime2' "$contract"
grep -q 'No recursion' "$contract"
grep -q 'No dynamic callee lowering' "$contract"
grep -q 'No arbitrary cross-module lowering' "$contract"
grep -q 'No reflective raw-body lowering API' "$contract"
grep -q 'No stable non-experimental runtime-call lowering API' "$contract"
grep -q 'No performance contract' "$contract"
grep -q 'docs/source_lowering_matrix.json' "$contract"
grep -q 'docs/source_lowering_coverage_matrix.json' "$contract"
grep -q 'docs/lowering_equivalence_report.json' "$contract"
grep -q 'docs/lowering_rejection_report.json' "$contract"
grep -q 'coverage_status' "$contract"
grep -q 'zig build source-lowering-coverage-check' "$contract"
grep -q 'zig build lowering-equivalence-report-check' "$contract"
grep -q 'zig build lowering-rejection-report-check' "$contract"
grep -q 'zig build test' "$contract"
grep -q 'not a public root API lane' "$contract"
grep -q 'b.step("kernel-source-lowering-check"' "$build_file"
grep -q 'b.step("source-lower"' "$build_file"
! grep -q 'b.step("source-lowering-gauntlet"' "$build_file"
grep -q 'open_row_state_writer' "$repo_root/test/example_proof_suite.zig"
