// Frozen BPI1 data/validation from Boundary 1.8.2, commit
// 999e936c4a865cd31948b52b2af2baeacf84c9f1. MIT license. No evaluator.
pub const FailureRole = enum {
    arithmetic_overflow,
    division_by_zero,
    capacity_exceeded,
    invalid_utf8,
    invalid_index,
    invalid_variant,
};

pub const WireOperation = enum(u16) {
    constant = 0,
    copy = 1,
    compare_eq_zero = 2,
    integer_add = 3,
    integer_subtract = 4,
    integer_multiply = 5,
    integer_divide = 6,
    integer_remainder = 7,
    integer_negate = 8,
    integer_equal = 9,
    integer_not_equal = 10,
    integer_less_than = 11,
    integer_less_equal = 12,
    integer_greater_than = 13,
    integer_greater_equal = 14,
    integer_bit_not = 15,
    integer_bit_and = 16,
    integer_bit_or = 17,
    integer_bit_xor = 18,
    integer_convert = 19,
    boolean_not = 20,
    boolean_and = 21,
    boolean_or = 22,
    select = 23,
    product_construct = 24,
    product_extract = 25,
    product_replace = 26,
    sum_construct = 27,
    sum_tag_is = 28,
    sum_extract = 29,
    optional_none = 30,
    optional_some = 31,
    optional_is_some = 32,
    vector_empty = 33,
    vector_length = 34,
    vector_get = 35,
    vector_set = 36,
    vector_push = 37,
    vector_pop = 38,
    vector_truncate = 39,
    vector_clear = 40,
    text_empty = 41,
    text_append = 42,
    text_append_scalar = 43,
    text_append_unsigned = 44,
    text_append_signed = 45,
    text_copy = 46,
    text_compare = 47,
    text_join = 48,
    bytes_empty = 49,
    bytes_append = 50,
    bytes_copy = 51,
    bytes_compare = 52,
    text_length = 53,
    bytes_length = 54,
    bytes_append_scalar = 55,
    bytes_join = 56,
    enum_to_u32 = 57,
    text_byte_at = 58,
    bytes_byte_at = 59,
};

pub fn fixedOperandCount(operation: WireOperation) ?u16 {
    return switch (operation) {
        .product_construct, .sum_construct => null,
        .constant,
        .optional_none,
        .vector_empty,
        .text_empty,
        .bytes_empty,
        => 0,
        .copy,
        .compare_eq_zero,
        .integer_negate,
        .integer_bit_not,
        .integer_convert,
        .boolean_not,
        .product_extract,
        .sum_tag_is,
        .sum_extract,
        .optional_some,
        .optional_is_some,
        .vector_length,
        .vector_pop,
        .vector_clear,
        .text_length,
        .bytes_length,
        .enum_to_u32,
        => 1,
        .integer_add,
        .integer_subtract,
        .integer_multiply,
        .integer_divide,
        .integer_remainder,
        .integer_equal,
        .integer_not_equal,
        .integer_less_than,
        .integer_less_equal,
        .integer_greater_than,
        .integer_greater_equal,
        .integer_bit_and,
        .integer_bit_or,
        .integer_bit_xor,
        .boolean_and,
        .boolean_or,
        .product_replace,
        .vector_get,
        .vector_push,
        .vector_truncate,
        .text_append,
        .text_append_scalar,
        .text_append_unsigned,
        .text_append_signed,
        .text_compare,
        .bytes_append,
        .bytes_append_scalar,
        .bytes_compare,
        .text_byte_at,
        .bytes_byte_at,
        => 2,
        .select,
        .vector_set,
        .text_copy,
        .text_join,
        .bytes_copy,
        .bytes_join,
        => 3,
    };
}

pub fn failureRoleName(role: FailureRole) []const u8 {
    return @tagName(role);
}

pub fn currentSemanticTagForWire(operation: WireOperation) u8 {
    return @intCast(@intFromEnum(operation) + 1);
}

pub fn failureRolesForWire(operation: WireOperation) []const FailureRole {
    return switch (operation) {
        .integer_add,
        .integer_subtract,
        .integer_multiply,
        .integer_negate,
        .integer_convert,
        => &.{.arithmetic_overflow},
        .integer_divide, .integer_remainder => &.{
            .arithmetic_overflow,
            .division_by_zero,
        },
        .sum_extract => &.{.invalid_variant},
        .vector_get, .vector_set, .text_byte_at, .bytes_byte_at => &.{.invalid_index},
        .text_append_scalar, .text_copy => &.{
            .capacity_exceeded,
            .invalid_utf8,
        },
        .vector_push,
        .text_append,
        .text_append_unsigned,
        .text_append_signed,
        .text_join,
        .bytes_append,
        .bytes_append_scalar,
        .bytes_copy,
        .bytes_join,
        => &.{.capacity_exceeded},
        .constant,
        .copy,
        .compare_eq_zero,
        .integer_equal,
        .integer_not_equal,
        .integer_less_than,
        .integer_less_equal,
        .integer_greater_than,
        .integer_greater_equal,
        .integer_bit_not,
        .integer_bit_and,
        .integer_bit_or,
        .integer_bit_xor,
        .boolean_not,
        .boolean_and,
        .boolean_or,
        .select,
        .product_construct,
        .product_extract,
        .product_replace,
        .sum_construct,
        .sum_tag_is,
        .optional_none,
        .optional_some,
        .optional_is_some,
        .vector_empty,
        .vector_length,
        .vector_pop,
        .vector_truncate,
        .vector_clear,
        .text_empty,
        .text_compare,
        .bytes_empty,
        .bytes_compare,
        .text_length,
        .bytes_length,
        .enum_to_u32,
        => &.{},
    };
}
