#!/usr/bin/env sh
set -eu

repo_root="$(CDPATH= cd -- "$(dirname "$0")/../.." && pwd)"
readme="$repo_root/README.md"
build_file="$repo_root/build.zig"

[ -f "$readme" ] || {
  echo "missing README.md" >&2
  exit 1
}

grep -q '^## Proof Surface$' "$readme"
grep -q '^## Executable Contract$' "$readme"
grep -q '^## Benchmark Contract$' "$readme"
grep -q '^## Formal Core$' "$readme"
grep -q 'zig build compile-fail' "$readme"
grep -q 'zig build example-proof' "$readme"
grep -q 'zig build backend-parity' "$readme"
grep -q 'zig build proof-fixtures-write' "$readme"
grep -q 'zig build proof-fixtures-check' "$readme"
grep -q 'zig build authoring-lowering-write' "$readme"
grep -q 'zig build authoring-lowering-check' "$readme"
grep -q 'zig build structured-program-suite' "$readme"
grep -q 'zig build direct-style-bridge-parity' "$readme"
grep -q 'zig build direct-style-boundary' "$readme"
grep -q 'zig build runtime-route-matrix-write' "$readme"
grep -q 'zig build runtime-route-matrix-check' "$readme"
grep -q 'zig build runtime-obligation-matrix-write' "$readme"
grep -q 'zig build runtime-obligation-matrix-check' "$readme"
grep -q 'zig build runtime-contract-suite' "$readme"
grep -q 'zig build runtime-error-surface-matrix-write' "$readme"
grep -q 'zig build runtime-error-surface-matrix-check' "$readme"
grep -q 'zig build root-surface-migration-matrix-write' "$readme"
grep -q 'zig build root-surface-migration-matrix-check' "$readme"
grep -q 'zig build shipped-surface-frontier-matrix-write' "$readme"
grep -q 'zig build shipped-surface-frontier-matrix-check' "$readme"
grep -q 'zig build canonical-raw-dependency-matrix-write' "$readme"
grep -q 'zig build canonical-raw-dependency-matrix-check' "$readme"
grep -q 'zig build frontend-feature-matrix-write' "$readme"
grep -q 'zig build frontend-feature-matrix-check' "$readme"
grep -q 'zig build shipped-backend-check' "$readme"
grep -q 'zig build surface-truth-scorecard-write' "$readme"
grep -q 'zig build surface-truth-scorecard-check' "$readme"
grep -q 'zig build formal-core-write' "$readme"
grep -q 'zig build formal-core' "$readme"
grep -q 'zig build run-exception-basic' "$readme"
grep -q 'zig build run-algebraic-abortive-validation' "$readme"
grep -q 'zig build run-algebraic-artifact-search' "$readme"
grep -q 'zig build run-optional-basic' "$readme"
grep -q 'zig build run-resource-basic' "$readme"
grep -q 'zig build run-writer-basic' "$readme"
grep -q 'zig build bench-effect-matrix' "$readme"
grep -q 'zig build bench-effect-matrix-stability' "$readme"
grep -q 'zig build bench-effect-matrix-write' "$readme"
grep -q 'zig build bench-effect-matrix-check' "$readme"
grep -q 'zig build bench-runtime-backends' "$readme"
grep -q 'zig build bench-runtime-backends-stability' "$readme"
grep -q 'zig build bench-runtime-backends-write' "$readme"
grep -q 'zig build bench-runtime-backends-check' "$readme"
grep -q 'zig build bench-state-effect-write' "$readme"
grep -q 'zig build bench-state-effect-check' "$readme"
grep -q 'effect_exception_forged_context_throw_fails.zig' "$readme"
grep -q 'effect_optional_forged_context_request_fails.zig' "$readme"
grep -q 'effect_reader_forged_context_ask_fails.zig' "$readme"
grep -q 'effect_resource_forged_context_acquire_fails.zig' "$readme"
grep -q 'effect_state_forged_context_get_fails.zig' "$readme"
grep -q 'effect_writer_forged_context_tell_fails.zig' "$readme"
grep -q 'shift.algebraic.TransformOp' "$readme"
grep -q 'shift.algebraic.Program' "$readme"
grep -q 'FORMAL_CORE.md' "$readme"
grep -q 'effect_family_matrix_v2.json' "$readme"
grep -q 'micro' "$readme"
grep -q 'amortized' "$readme"
grep -q 'investigation' "$readme"
grep -q 'effect-construction-boundary' "$readme"
grep -q 'src/parity_machine.zig' "$readme"
grep -q 'src/parity_kernel.zig' "$readme"
grep -q 'src/lowered_machine.zig' "$readme"
grep -q 'src/parity_scenarios.zig' "$readme"
grep -q 'src/program_frontend.zig' "$readme"
grep -q 'src/program_bridge.zig' "$readme"
grep -q 'src/private_lowered_runtime.zig' "$readme"
grep -q 'docs/runtime_obligation_matrix.json' "$readme"
grep -q 'tools/render_runtime_obligation_matrix.zig' "$readme"
grep -q 'docs/runtime_error_surface_matrix.json' "$readme"
grep -q 'tools/render_runtime_error_surface_matrix.zig' "$readme"
grep -q 'docs/root_surface_migration_matrix.json' "$readme"
grep -q 'tools/render_root_surface_migration_matrix.zig' "$readme"
grep -q 'docs/shipped_surface_frontier_matrix.json' "$readme"
grep -q 'tools/render_shipped_surface_frontier_matrix.zig' "$readme"
grep -q 'docs/canonical_raw_dependency_matrix.json' "$readme"
grep -q 'tools/render_canonical_raw_dependency_matrix.zig' "$readme"
grep -q 'docs/frontend_feature_matrix.json' "$readme"
grep -q 'tools/render_frontend_feature_matrix.zig' "$readme"
grep -q 'src/compat/raw.zig' "$readme"
grep -q 'docs/runtime_route_matrix.json' "$readme"
grep -q 'tools/render_runtime_route_matrix.zig' "$readme"
grep -q 'src/runtime_stack_baseline.zig' "$readme"
grep -q 'tools/render_proof_fixtures.zig' "$readme"
grep -q 'tools/render_authoring_lowerings.zig' "$readme"
grep -q 'tools/render_surface_truth_scorecard.zig' "$readme"
grep -q 'docs/surface_truth_scorecard.json' "$readme"
grep -q 'docs/direct_style_boundary.md' "$readme"

grep -q 'formal-core-write' "$build_file"
grep -q 'formal-core' "$build_file"
grep -q 'backend-parity' "$build_file"
grep -q 'proof-fixtures-write' "$build_file"
grep -q 'proof-fixtures-check' "$build_file"
grep -q 'authoring-lowering-write' "$build_file"
grep -q 'authoring-lowering-check' "$build_file"
grep -q 'structured-program-suite' "$build_file"
grep -q 'direct-style-bridge-parity' "$build_file"
grep -q 'direct-style-boundary' "$build_file"
grep -q 'runtime-route-matrix-write' "$build_file"
grep -q 'runtime-route-matrix-check' "$build_file"
grep -q 'runtime-obligation-matrix-write' "$build_file"
grep -q 'runtime-obligation-matrix-check' "$build_file"
grep -q 'runtime-contract-suite' "$build_file"
grep -q 'runtime-error-surface-matrix-write' "$build_file"
grep -q 'runtime-error-surface-matrix-check' "$build_file"
grep -q 'root-surface-migration-matrix-write' "$build_file"
grep -q 'root-surface-migration-matrix-check' "$build_file"
grep -q 'shipped-surface-frontier-matrix-write' "$build_file"
grep -q 'shipped-surface-frontier-matrix-check' "$build_file"
grep -q 'canonical-raw-dependency-matrix-write' "$build_file"
grep -q 'canonical-raw-dependency-matrix-check' "$build_file"
grep -q 'frontend-feature-matrix-write' "$build_file"
grep -q 'frontend-feature-matrix-check' "$build_file"
grep -q 'shipped-backend-check' "$build_file"
grep -q 'surface-truth-scorecard-write' "$build_file"
grep -q 'surface-truth-scorecard-check' "$build_file"
grep -q 'bench-effect-matrix' "$build_file"
grep -q 'bench-effect-matrix-stability' "$build_file"
grep -q 'bench-effect-matrix-write' "$build_file"
grep -q 'bench-effect-matrix-check' "$build_file"
grep -q 'bench-runtime-backends' "$build_file"
grep -q 'bench-runtime-backends-stability' "$build_file"
grep -q 'bench-runtime-backends-write' "$build_file"
grep -q 'bench-runtime-backends-check' "$build_file"
grep -q 'effect-construction-boundary' "$build_file"
grep -q 'bench-state-effect-write' "$build_file"
grep -q 'bench-state-effect-check' "$build_file"
grep -q 'run-exception-basic' "$build_file"
grep -q 'run-algebraic-abortive-validation' "$build_file"
grep -q 'run-algebraic-artifact-search' "$build_file"
grep -q 'run-optional-basic' "$build_file"
grep -q 'run-resource-basic' "$build_file"
grep -q 'run-writer-basic' "$build_file"
