#!/usr/bin/env sh
set -eu

repo_root="$(CDPATH= cd -- "$(dirname "$0")/../.." && pwd)"
readme="$repo_root/README.md"
build_file="$repo_root/build.zig"

[ -f "$readme" ] || {
  echo "missing README.md" >&2
  exit 1
}

grep -q '^## Proof Surface$' "$readme"
grep -q '^## Executable Contract$' "$readme"
grep -q '^## Benchmark Contract$' "$readme"
grep -q '^## Formal Core$' "$readme"

grep -q 'agentic systems' "$readme"
grep -q 'generalized algebraic' "$readme"
grep -q 'programmable control systems' "$readme"
grep -q 'WASM' "$readme"
grep -q 'defunctionalized program data' "$readme"
grep -q '`shift.with(...)`' "$readme"
grep -q '`shift.effect.*`' "$readme"
grep -q '`shift.effect.Define(...)`' "$readme"
grep -q '`shift_compile.ir`' "$readme"
grep -q '`shift_compile.lowering`' "$readme"
grep -q '`shift_compile.lower`' "$readme"
grep -q 'retained compatibility, runtime, and proof surfaces' "$readme"
grep -q '`shift_vm.Program(...)`, `shift_vm.Decl`, `shift_vm.Op`,' "$readme"
grep -q '`shift_vm.Decision(...)`, `shift_vm.run(...)`, `shift_vm.interpreter`,' "$readme"
grep -q '`shift_vm.durable`, and `shift_vm.ErrorWitnessV1` as retained compatibility' "$readme"
grep -q 'witness ids, bridge case ids, source corpus ids, and legacy fixture names as' "$readme"
grep -q 'retired root spellings are checked by tombstone proofs instead of' "$readme"
grep -q 'tombstone proofs' "$readme"
grep -q 'Retired root spellings are gone from the' "$readme"
grep -q 'no public continuation handle exported' "$readme"
grep -q 'not a generic effect framework' "$readme"
grep -q 'current shipped surface contract' "$readme"
grep -q 'item=query=artifact-search' "$readme"
grep -q 'item=workflow=queued' "$readme"
grep -q 'final_state=6' "$readme"
grep -q 'value=done' "$readme"
grep -q 'open_row_state_writer` is still a retained proof label only' "$readme"

! grep -q '`Program.Manifest`' "$readme"
! grep -q 'shift.algebraic.' "$readme"
! grep -q 'shift.ordinary' "$readme"
! grep -q 'ordinary-Zig experimental track' "$readme"
! grep -q 'legacy-compatible' "$readme"
! grep -q 'shift.runWith(' "$readme"

grep -q 'zig build source-lowering-coverage-check' "$readme"
grep -q 'zig build source-lowering-coverage-matrix-write' "$readme"
grep -q 'zig build source-lower' "$readme"
grep -q 'zig build source-lowering-error-witness-check' "$readme"
grep -q 'zig build bench-family-matrix' "$readme"
grep -q 'zig build bench-family-matrix-stability' "$readme"
grep -q 'zig build bench-family-matrix-write' "$readme"
grep -q 'zig build bench-family-matrix-check' "$readme"
grep -q 'zig build public-root-contract-snapshot-check' "$readme"
grep -q 'zig build public-error-api-ban' "$readme"
grep -q 'zig build retired-lane-inventory-check' "$readme"

grep -q 'source-lowering cases' "$readme"
grep -q 'internal proof infrastructure' "$readme"
grep -q 'src/shift_compile.zig' "$readme"
grep -q 'src/shift_vm.zig' "$readme"
grep -q 'docs/direct_style_boundary.md' "$readme"
grep -q 'docs/source_lowering_contract.md' "$readme"

grep -q 'b.step("kernel-parity-check"' "$build_file"
grep -q 'b.step("kernel-source-lowering-check"' "$build_file"
grep -q 'source-lowering-coverage-check' "$build_file"
grep -q 'source-lowering-coverage-matrix-write' "$build_file"
grep -q 'b.step("source-lower"' "$build_file"
grep -q 'source-lowering-error-witness-check' "$build_file"
grep -q 'bench-family-matrix' "$build_file"
grep -q 'bench-family-matrix-stability' "$build_file"
grep -q 'bench-family-matrix-write' "$build_file"
grep -q 'bench-family-matrix-check' "$build_file"
grep -q 'bench-family-builder-decompose' "$build_file"
grep -q 'public-root-contract-snapshot-check' "$build_file"
grep -q 'public-error-api-ban' "$build_file"
grep -q 'retired-lane-inventory-check' "$build_file"
grep -q 'test_step.dependOn(&run_size_tests.step);' "$build_file"

! grep -q 'b.step("backend-parity"' "$build_file"
! grep -q 'b.step("source-lowering-gauntlet"' "$build_file"
! grep -q 'b.step("direct-style-bridge-parity"' "$build_file"
grep -q 'b.step("runtime-route-matrix-check"' "$build_file"
grep -q 'b.step("runtime-route-matrix-write"' "$build_file"
grep -q 'b.step("runtime-obligation-matrix-check"' "$build_file"
grep -q 'b.step("runtime-obligation-matrix-write"' "$build_file"
! grep -q 'b.step("shipped-backend-check"' "$build_file"
! grep -q 'ordinary-zig-gauntlet' "$build_file"
! grep -q 'ordinary-lower' "$build_file"
! grep -q 'ordinary-error-witness-check' "$build_file"
! grep -q 'bench-effect-matrix' "$build_file"
! grep -q 'bench-algebraic-decompose' "$build_file"
! grep -q 'shared-algebraic-engine-boundary' "$build_file"
