#!/usr/bin/env sh
set -eu

repo_root="$(CDPATH= cd -- "$(dirname "$0")/../.." && pwd)"
readme="$repo_root/README.md"
build_file="$repo_root/build.zig"

[ -f "$readme" ] || {
  echo "missing README.md" >&2
  exit 1
}

grep -q '^## Proof Surface$' "$readme"
grep -q '^## Executable Contract$' "$readme"
grep -q '^## Benchmark Contract$' "$readme"
grep -q '^## Formal Core$' "$readme"

grep -q 'root-level execution kernel' "$readme"
grep -q '`shift.Runtime` ownership, `shift.run(...)`, and the public result/error' "$readme"
grep -q '`shift.RuntimeError`,' "$readme"
grep -q '`shift.ErrorWitnessV1`, `shift.Decl`, `shift.Op`, `shift.Decision(...)`,' "$readme"
grep -q '`shift.Program(...)`, and `shift.run(...)`' "$readme"
grep -q 'current authoring frontends lower into that kernel; they are implementation' "$readme"
grep -q 'witness ids, bridge case ids, source corpus ids, and legacy fixture names are' "$readme"
grep -q 'retired root spellings are checked by tombstone proofs instead of' "$readme"
grep -q 'compatibility narratives' "$readme"
grep -q 'Retired root spellings are gone from the shipped root' "$readme"
grep -q 'no public continuation handle is exported' "$readme"

! grep -q '`Program.Manifest`' "$readme"
! grep -q 'shift.with(' "$readme"
! grep -q 'shift.effect.' "$readme"
! grep -q 'shift.algebraic.' "$readme"
! grep -q 'shift.ordinary' "$readme"
! grep -q 'ordinary-Zig experimental track' "$readme"
! grep -q 'compatibility layer' "$readme"
! grep -q 'legacy-compatible' "$readme"
! grep -q 'shift.runWith(' "$readme"

grep -q 'zig build source-lowering-coverage-check' "$readme"
grep -q 'zig build source-lowering-coverage-matrix-write' "$readme"
grep -q 'zig build source-lower' "$readme"
grep -q 'zig build source-lowering-error-witness-check' "$readme"
grep -q 'zig build bench-family-matrix' "$readme"
grep -q 'zig build bench-family-matrix-stability' "$readme"
grep -q 'zig build bench-family-matrix-write' "$readme"
grep -q 'zig build bench-family-matrix-check' "$readme"
grep -q 'zig build public-root-contract-snapshot-check' "$readme"
grep -q 'zig build public-error-api-ban' "$readme"
grep -q 'zig build retired-lane-inventory-check' "$readme"

grep -q 'source-lowering coverage for internal witnesses, internal fixture/example ids,' "$readme"
grep -q 'docs/direct_style_boundary.md' "$readme"
grep -q 'docs/source_lowering_contract.md' "$readme"

grep -q 'b.step("kernel-parity-check"' "$build_file"
grep -q 'b.step("kernel-source-lowering-check"' "$build_file"
grep -q 'source-lowering-coverage-check' "$build_file"
grep -q 'source-lowering-coverage-matrix-write' "$build_file"
grep -q 'b.step("source-lower"' "$build_file"
grep -q 'source-lowering-error-witness-check' "$build_file"
grep -q 'bench-family-matrix' "$build_file"
grep -q 'bench-family-matrix-stability' "$build_file"
grep -q 'bench-family-matrix-write' "$build_file"
grep -q 'bench-family-matrix-check' "$build_file"
grep -q 'bench-family-builder-decompose' "$build_file"
grep -q 'public-root-contract-snapshot-check' "$build_file"
grep -q 'public-error-api-ban' "$build_file"
grep -q 'retired-lane-inventory-check' "$build_file"
grep -q 'test_step.dependOn(&run_size_tests.step);' "$build_file"

! grep -q 'b.step("backend-parity"' "$build_file"
! grep -q 'b.step("source-lowering-gauntlet"' "$build_file"
! grep -q 'b.step("direct-style-bridge-parity"' "$build_file"
! grep -q 'b.step("runtime-route-matrix-check"' "$build_file"
! grep -q 'b.step("runtime-route-matrix-write"' "$build_file"
! grep -q 'b.step("runtime-obligation-matrix-check"' "$build_file"
! grep -q 'b.step("runtime-obligation-matrix-write"' "$build_file"
! grep -q 'b.step("shipped-backend-check"' "$build_file"
! grep -q 'ordinary-zig-gauntlet' "$build_file"
! grep -q 'ordinary-lower' "$build_file"
! grep -q 'ordinary-error-witness-check' "$build_file"
! grep -q 'bench-effect-matrix' "$build_file"
! grep -q 'bench-algebraic-decompose' "$build_file"
! grep -q 'shared-algebraic-engine-boundary' "$build_file"
