// Generates ordinary Lean definitions and proofs for the finite profile record
// shapes. The generator is untrusted: Lean checks every isomorphism and codec
// law, and independent Zig wire cases check the assigned tags and field order.
import { writeFile, readFile } from 'node:fs/promises';
import { fileURLToPath } from 'node:url';
const output = fileURLToPath(new URL('../../semantics/v2/BoundaryV2/ProfileCodec.lean', import.meta.url));
const nat = 'NonemptyCodec.natural', bool = 'NonemptyCodec.boolean', blob = 'NonemptyCodec.blob';
const ref = (domain, space='space') => `(NonemptyCodec.reference ${space} .${domain})`;
const refs = (domain, space='space') => `${ref(domain,space)}.list`;
const list = (codec) => `(${codec}).list`;
const optional = (codec) => `(NonemptyCodec.optional (${codec}).toCodec)`;
const rtype = (domain,space='space') => `Ref ${space} .${domain}`;
const pair = (codecs) => codecs.length === 1 ? codecs[0] : `(${codecs[0]}.pair (${pair(codecs.slice(1))}).toCodec)`;
const tupleType = (types) => types.length === 0 ? 'Unit' : types.length === 1 ? types[0] : `(${types.join(' × ')})`;
const tupleValue = (values) => values.length === 0 ? '()' : values.length === 1 ? values[0] : `(${values.join(', ')})`;
let code = `import BoundaryV2.Wire\n\n/- Generated by tools/v2/generate_profile_codecs.mjs. These are raw wire\ncodecs: semantic admission and canonical graph numbering are separate checks. -/\nnamespace BoundaryV2.Profile.Codecs\nopen Wire\n\n`;
function enumeration(name, type, variants) {
  code += `def ${name}Values : List ${type} := [${variants.map(v=>'.'+v).join(', ')}]\n\n`;
  code += `def ${name}Name : ${type} → String\n`;
  for (const variant of variants) code += `  | .${variant} => "${variant.replace(/[A-Z]/g, c=>'_'+c.toLowerCase())}"\n`;
  code += `\ndef ${name} : NonemptyCodec ${type} :=\n  NonemptyCodec.enumeration ${name}Values\n    (by intro value; cases value <;> simp [${name}Values]) (by decide) (by decide)\n\n`;
}
function record(name, type, fields, generic=false) {
  const values=fields.map((_,i)=>`v${i}`), pattern=tupleValue(values);
  const codec=pair(fields.map(f=>f[1]));
  code+=`def ${name}${generic?' (space : Space)':''} : NonemptyCodec (${type}) :=\n  ${codec}.iso\n    (fun ${pattern} => { ${fields.map((f,i)=>f[0]+' := '+values[i]).join(', ')} })\n    (fun value => ${tupleValue(fields.map(f=>'value.'+f[0]))})\n    (by intro value; cases value; rfl)\n    (by intro value; ${fields.length===1?'':`rcases value with ⟨${values.join(', ')}⟩; `}rfl)\n\n`;
}
function union(name,type,cases,generic=false) {
  const tag=name[0].toUpperCase()+name.slice(1)+'Tag', payload=name+'Payload', view=name+'View';
  const parameter=generic?' (space : Space)':'', argument=generic?' space':'';
  code+=`inductive ${tag} where\n  | ${cases.map(c=>c[0]).join(' | ')}\n  deriving DecidableEq, Repr\n\n`;
  enumeration(name+'Tag',tag,cases.map(c=>c[0]));
  code+=`def ${payload}${parameter} : ${tag} → Type\n`;
  for(const [name,fields]of cases)code+=`  | .${name} => ${tupleType(fields.map(f=>f[0]))}\n`;
  code+=`\ndef ${view}${parameter} : ${type} → Sigma (${payload}${argument})\n`;
  for(const [ctor,fields]of cases){const vs=fields.map((_,i)=>`v${i}`);code+=`  | .${ctor}${vs.length?' '+vs.join(' '):''} => ⟨.${ctor}, ${tupleValue(vs)}⟩\n`;}
  code+=`\ndef ${name}OfView${parameter} : Sigma (${payload}${argument}) → ${type}\n`;
  for(const [ctor,fields]of cases){const vs=fields.map((_,i)=>`v${i}`);code+=`  | ⟨.${ctor}, ${fields.length?tupleValue(vs):'_'}⟩ => .${ctor}${vs.length?' '+vs.join(' '):''}\n`;}
  code+=`\ndef ${name}Fields${parameter} : (tag : ${tag}) → Codec (${payload}${argument} tag)\n`;
  for(const [ctor,fields]of cases)code+=`  | .${ctor} => ${fields.length?`(${pair(fields.map(f=>f[1]))}).toCodec`:'Codec.unit'}\n`;
  code+=`\ndef ${name}${parameter} : NonemptyCodec (${type}) :=\n  (NonemptyCodec.dependent ${name}Tag (${name}Fields${argument})).iso\n    (${name}OfView${argument}) (${view}${argument})\n    (by intro value; cases value <;> rfl)\n    (by rintro ⟨tag, data⟩; cases tag with\n`;
  for(const [ctor,fields]of cases)code+=`      | ${ctor} => ${fields.length===0?'cases data; ':fields.length>1?`rcases data with ⟨${fields.map((_,i)=>'v'+i).join(', ')}⟩; `:''}rfl\n`;
  code+=`    )\n\n`;
}
enumeration('use','Use',['reusable','affine','linear','multi']);
enumeration('mode','Mode',['deep','shallow']);
enumeration('fault','Fault',['arithmeticOverflow','divisionByZero','capacityExceeded','invalidUtf8','invalidIndex','invalidVariant']);
enumeration('opcode','Opcode',['constant','move','integerAdd','integerSub','integerMul','integerDiv','equal','less','booleanNot','product','field','variant','variantTag','variantPayload','sequence','sequenceLength','sequenceGet','sequenceAppend','sequenceConcat','sequencePop','computation','cellNew','cellGet','cellSet','cloneResumption','package','unpack','resourcePack','resourceUnpack','integerRem','integerBitNot','integerBitAnd','integerBitOr','integerBitXor','integerConvert','enumTag','blobLength','blobConcat','blobSlice','blobCompare','blobByte','textScalar','textInteger','sequenceSet','sequenceTake','blobFromByte','sequencePopLast','select']);
record('computationType','ComputationType space',[['parameters',refs('schema')],['result',ref('schema')],['effects',refs('effect')],['captureBound',refs('schema')],['use','use'],['regions',refs('regionBinder')]],true);
record('resumptionType','ResumptionType space',[['effect',ref('effect')],['input',ref('schema')],['answer',ref('schema')],['effects',refs('effect')],['captureBound',refs('schema')],['handled',refs('effect')],['escaping',refs('effect')],['mode','mode'],['use','use'],['ownedRegions',refs('regionBinder')],['obligations',bool]],true);
union('internal','Internal space',[
 ['computation',[['ComputationType space','(computationType space)']]],
 ['capability',[[rtype('effect'),ref('effect')]]],
 ['cell',[[rtype('schema'),ref('schema')],[rtype('regionBinder'),ref('regionBinder')]]],
 ['region',[[rtype('regionBinder'),ref('regionBinder')]]],
 ['resumption',[['ResumptionType space','(resumptionType space)']]],
 ['suspensionPackage',[[rtype('schema'),ref('schema')]]],
 ['abstractResource',[[rtype('resource'),ref('resource')]]],
 ['borrowed',[[rtype('schema'),ref('schema')],[rtype('regionBinder'),ref('regionBinder')]]],
],true);
code+=`def enumerationTags : NonemptyCodec (List Nat) :=\n  (NonemptyCodec.natural.checked fun value => decide (value < 2 ^ 32)).list\n\n`;
union('schema','Schema space',[
 ...['unit','boolean','i8','i16','i32','i64','u8','u16','u32','u64','bytes','text'].map(name=>[name,[]]),
 ['product',[[`List (${rtype('schema')})`,refs('schema')]]],['sum',[[`List (${rtype('schema')})`,refs('schema')]]],
 ['seq',[[rtype('schema'),ref('schema')]]],['vector',[[rtype('schema'),ref('schema')],['Nat',nat]]],
 ['internal',[['Internal space','(internal space)']]],['array',[[rtype('schema'),ref('schema')],['Nat',nat]]],
 ['boundedBytes',[['Nat',nat]]],['boundedText',[['Nat',nat]]],['enumeration',[['List Nat','enumerationTags']]],
],true);
record('literal','Literal space',[['schema',ref('schema')],['bytes',blob]],true);
record('effect','Effect space',[['identity',blob],['payload',ref('schema')],['result',ref('schema')],['useSiteEffects',refs('effect')],['bodies',refs('schema')],['controlUse','use'],['external',bool]],true);
record('instructionFailure','InstructionFailure space',[['kind','fault'],['value',ref('constant')]],true);
record('clause','Clause space',[['effect',ref('effect')],['function',ref('function')],['resumption',ref('schema')],['direct',bool]],true);
record('handler','Handler space',[['mode','mode'],['input',ref('schema')],['answer',ref('schema')],['returnFunction',ref('function')],['clauses',list('(clause space)')],['forwardFunction',optional(ref('function'))],['state',refs('schema')],['effects',refs('effect')]],true);
record('resource','Resource space',[['representation',ref('schema')],['introducers',refs('function')],['eliminators',refs('function')]],true);
const tr=d=>ref(d,'.target'), trs=d=>refs(d,'.target'), trt=d=>rtype(d,'.target');
record('slot','Target.Slot',[['value',nat]]);
union('argument','Target.Argument',[['slot',[['Target.Slot','slot']]],['returned',[]]]);
record('edge','Target.Edge',[['block',tr('block')],['arguments',list('argument')]]);
record('instruction','Target.Instruction',[['opcode','opcode'],['resultType',tr('schema')],['operands',list('slot')],['immediate',nat],['failures',list('(instructionFailure .target)')]]);
record('perform','Target.Perform',[['effect',tr('effect')],['capability',optional('slot')],['payload','slot'],['bodies',list('slot')],['useSiteCapabilities',list('slot')],['next','edge']]);
const sl=['Target.Slot','slot'], sls=['List Target.Slot',list('slot')], ed=['Target.Edge','edge'];
union('terminator','Target.Terminator',[
 ['returnValue',[sl]],['jump',[ed]],['branch',[sl,ed,ed]],['switchVariant',[sl,['List Target.Edge',list('edge')]]],
 ['unpackProduct',[sl,[trt('block'),tr('block')],sls]],['call',[[trt('function'),tr('function')],sls,ed]],
 ['perform',[['Target.Perform','perform']]],['yieldValue',[ed]],['fail',[sl]],['apply',[sl,sls,ed]],
 ['handle',[[trt('handler'),tr('handler')],sl,sls,sls,ed]],['resumeValue',[sl,sl,ed]],
 ['resumeWith',[sl,sl,[trt('handler'),tr('handler')],sls,ed]],['resumeComputation',[sl,sl,ed]],
 ['forward',[['Target.Perform','perform']]],['dispose',[sl,ed]],
 ['protect',[sl,sl,sls,['Option Target.Slot',optional('slot')],[`Option (${trt('regionBinder')})`,optional(tr('regionBinder'))],ed]],
 ['withRegion',[[trt('regionBinder'),tr('regionBinder')],sl,sls,ed]],
]);
record('block','Target.Block',[['function',tr('function')],['parameters',trs('schema')],['instructions',list('instruction')],['terminator','terminator']]);
record('function','Target.Function',[['entry',tr('block')],['parameters',trs('schema')],['result',tr('schema')],['effects',trs('effect')],['regions',trs('regionBinder')]]);
record('capture','Target.Capture',[['fields',trs('schema')],['ownedRegions',trs('regionBinder')],['borrowedRegions',trs('regionBinder')],['use','use']]);
record('constructor','Target.Constructor',[['function',tr('function')],['capture',tr('capture')],['schema',tr('schema')]]);
record('scopeCatalog','Target.ScopeCatalog',[['captures',list('capture')],['regionCount',nat],['resources',list('(resource .target)')]]);
record('programRoots','Target.Roots',[['profile',nat],['entry',tr('function')],['result',tr('schema')],['failure',tr('schema')]]);
record('rawProgram','Target.Program',[['roots','programRoots'],['schemas',list('(schema .target)')],['constants',list('(literal .target)')],['effects',list('(effect .target)')],['functions',list('function')],['blocks',list('block')],['handlers',list('(handler .target)')],['scopes','scopeCatalog'],['constructors',list('constructor')]]);

union('reason','Protocol.Reason',[['text',[['Bytes',blob]]],['bytes',[['Bytes',blob]]]]);
enumeration('invocationMode','Protocol.Mode',['advance','run']);
union('instanceData','Protocol.Instance',[['initialArgs',[['Bytes',blob]]],['state',[['Bytes',blob]]]]);
union('externalControl','Protocol.Control',[['continueValue',[['Option Bytes',optional(blob)]]],['cancel',[['Protocol.Reason','reason']]]]);
record('rawInput','Protocol.Input',[['mode','invocationMode'],['image',blob],['instanceData','instanceData'],['control','externalControl']]);
enumeration('provenance','Protocol.Provenance',['notObserved','exact','lowerBound']);
enumeration('arena','Protocol.Arena',['input','working','output','memory']);
record('bound','Protocol.Bound',[['amount',nat],['provenance','provenance']]);
record('capacity','Protocol.Capacity',[['arena','arena'],['input','bound'],['working','bound'],['output','bound'],['memoryPages','bound']]);
union('rawOutcome','Protocol.Outcome',[
 ['progressed',[['Bytes',blob]]],['requested',[['Bytes',blob],['Bytes',blob]]],['yielded',[['Bytes',blob]]],['completed',[['Bytes',blob]]],
 ['failed',[['Bytes',blob],['Bytes',blob],['Option Protocol.Reason',optional('reason')]]],
 ['cancelled',[['Protocol.Reason','reason'],['Bytes',blob]]],['needsCapacity',[['Protocol.Capacity','capacity']]],
]);
const digest='(NonemptyCodec.fixedBytes 32 (by decide))';
record('rawRequest','Protocol.Request',[['programIdentity',digest],['pendingStateDigest',digest],['residualContractDigest',digest],['continuationBindingDigest',digest],['semanticIdentity',blob],['payloadSchema',blob],['resumeSchema',blob],['payload',blob],['requestIdentity',digest]]);
record('rawResult','Protocol.Result',[['requestIdentity',digest],['resumeSchemaDigest',digest],['value',blob]]);

const nr=ref('node','.runtime'), nt='NodeId', or=optional(nr), ot='Option NodeId';
const sid=[trt('schema'),tr('schema')], bid=[trt('block'),tr('block')], node=[nt,nr], optNode=[ot,or];
record('ownedRef','Graph.OwnedRef',[['node',nr]]);
union('valueBody','Graph.ValueBody',[
 ['scalar',[['Vector UInt8 8','(NonemptyCodec.fixedBytes 8 (by decide))']]],
 ['blob',[['BlobId',ref('blob','.runtime')]]],['reference',[node]],['owned',[['Graph.OwnedRef','ownedRef']]],
]);
record('value','Graph.Value',[['schema',tr('schema')],['body','valueBody']]);
record('graphBlob','Graph.Blob',[['schema',tr('schema')],['bytes',blob]]);
record('control','Graph.Control',[['block',tr('block')],['arguments',list('value')],['parent',or],['evidence',or],['region',or]]);
record('continuation','Graph.Continuation',[['sourceBlock',tr('block')],['arguments',list(optional('value'))],['parent',or],['evidence',or],['region',or]]);
union('exitReason','Graph.ExitReason',[['normal',[['Graph.Value','value']]],['failure',[['Graph.Value','value']]],['cancellation',[]],['abandoned',[]]]);
record('exit','Graph.Exit',[['reason','exitReason'],['cleanupFailures',list('value')],['cancellation',optional('reason')],['stop',or],['outer',or],['discarded',list('value')]]);
record('captureState','Graph.Capture',[['schema',tr('schema')],['capture',or],['delimiter',nr],['evidence',or],['useSiteCapabilities',list('value')]]);
enumeration('attachmentPhase','Graph.AttachmentPhase',['active','suspended']);
union('obligationStatus','Graph.ObligationStatus',[['pending',[]],['running',[node]],['completed',[]],['failed',[['Graph.Value','value']]]]);
const v=['Graph.Value','value'], vs=['List Graph.Value',list('value')], ov=['Option Graph.Value',optional('value')], owned=['Graph.OwnedRef','ownedRef'];
union('node','Graph.Node',[
 ['control',[['Graph.Control','control']]],['continuation',[['Graph.Continuation','continuation']]],
 ['handler',[[trt('handler'),tr('handler')],vs,optNode,optNode]],
 ['attachment',[node,optNode,optNode,['Graph.AttachmentPhase','attachmentPhase'],optNode]],
 ['environment',[vs,optNode]],['aggregate',[sid,['Nat',nat],vs]],
 ['region',[[trt('regionBinder'),tr('regionBinder')],optNode,['List Graph.OwnedRef',list('ownedRef')]]],
 ['regionScope',[bid,node,optNode]],['injection',[node]],['protection',[bid,owned,optNode,optNode,optNode,optNode]],
 ['cleanupReturn',[owned,optNode,node]],['disposalReturn',[sid,optNode,vs]],['unwind',[optNode,vs]],['cell',[sid,node,ov]],
 ['oneShot',[['Graph.Capture','captureState']]],['multiTemplate',[['Graph.Capture','captureState']]],
 ['branch',[node,node,['List (NodeId × NodeId)',list(pair([nr,nr]))]]],['package',[sid,v]],
 ['computation',[[trt('constructor'),tr('constructor')],node]],['resource',[sid,v]],['borrow',[sid,node,node]],
 ['obligation',[bid,ov,ov,['Graph.ObligationStatus','obligationStatus']]],
 ['pending',[[trt('effect'),tr('effect')],v,node,bid]],['exit',[['Graph.Exit','exit']]],
]);
record('graphRoots','Graph.Roots',[['current',or],['evidence',or],['detached',list('ownedRef')],['exit',or],['pending',or]]);
enumeration('graphStatus','Graph.Status',['active','yielded','parked','unwinding']);
record('rawState','Graph.State',[['programIdentity',digest],['status','graphStatus'],['roots','graphRoots'],['nodes',list('node')],['blobs',list('graphBlob')]]);
code+='end BoundaryV2.Profile.Codecs\n';
if(process.argv[2]==='--check') {
 if(await readFile(output,'utf8')!==code) throw new Error('profile codecs differ from their generator');
} else {
 if(process.argv.length!==2) throw new Error('usage: generate_profile_codecs.mjs [--check]');
 await writeFile(output,code);
}
