import BoundaryV2.Wire

/- Generated by tools/v2/generate_profile_codecs.mjs. These are raw wire
codecs: semantic admission and canonical graph numbering are separate checks. -/
namespace BoundaryV2.Profile.Codecs
open Wire

def useValues : List Use := [.reusable, .affine, .linear, .multi]

def useName : Use → String
  | .reusable => "reusable"
  | .affine => "affine"
  | .linear => "linear"
  | .multi => "multi"

def use : NonemptyCodec Use :=
  NonemptyCodec.enumeration useValues
    (by intro value; cases value <;> simp [useValues]) (by decide) (by decide)

def modeValues : List Mode := [.deep, .shallow]

def modeName : Mode → String
  | .deep => "deep"
  | .shallow => "shallow"

def mode : NonemptyCodec Mode :=
  NonemptyCodec.enumeration modeValues
    (by intro value; cases value <;> simp [modeValues]) (by decide) (by decide)

def faultValues : List Fault := [.arithmeticOverflow, .divisionByZero, .capacityExceeded, .invalidUtf8, .invalidIndex, .invalidVariant]

def faultName : Fault → String
  | .arithmeticOverflow => "arithmetic_overflow"
  | .divisionByZero => "division_by_zero"
  | .capacityExceeded => "capacity_exceeded"
  | .invalidUtf8 => "invalid_utf8"
  | .invalidIndex => "invalid_index"
  | .invalidVariant => "invalid_variant"

def fault : NonemptyCodec Fault :=
  NonemptyCodec.enumeration faultValues
    (by intro value; cases value <;> simp [faultValues]) (by decide) (by decide)

def opcodeValues : List Opcode := [.constant, .move, .integerAdd, .integerSub, .integerMul, .integerDiv, .equal, .less, .booleanNot, .product, .field, .variant, .variantTag, .variantPayload, .sequence, .sequenceLength, .sequenceGet, .sequenceAppend, .sequenceConcat, .sequencePop, .computation, .cellNew, .cellGet, .cellSet, .cloneResumption, .package, .unpack, .resourcePack, .resourceUnpack, .integerRem, .integerBitNot, .integerBitAnd, .integerBitOr, .integerBitXor, .integerConvert, .enumTag, .blobLength, .blobConcat, .blobSlice, .blobCompare, .blobByte, .textScalar, .textInteger, .sequenceSet, .sequenceTake, .blobFromByte, .sequencePopLast, .select]

def opcodeName : Opcode → String
  | .constant => "constant"
  | .move => "move"
  | .integerAdd => "integer_add"
  | .integerSub => "integer_sub"
  | .integerMul => "integer_mul"
  | .integerDiv => "integer_div"
  | .equal => "equal"
  | .less => "less"
  | .booleanNot => "boolean_not"
  | .product => "product"
  | .field => "field"
  | .variant => "variant"
  | .variantTag => "variant_tag"
  | .variantPayload => "variant_payload"
  | .sequence => "sequence"
  | .sequenceLength => "sequence_length"
  | .sequenceGet => "sequence_get"
  | .sequenceAppend => "sequence_append"
  | .sequenceConcat => "sequence_concat"
  | .sequencePop => "sequence_pop"
  | .computation => "computation"
  | .cellNew => "cell_new"
  | .cellGet => "cell_get"
  | .cellSet => "cell_set"
  | .cloneResumption => "clone_resumption"
  | .package => "package"
  | .unpack => "unpack"
  | .resourcePack => "resource_pack"
  | .resourceUnpack => "resource_unpack"
  | .integerRem => "integer_rem"
  | .integerBitNot => "integer_bit_not"
  | .integerBitAnd => "integer_bit_and"
  | .integerBitOr => "integer_bit_or"
  | .integerBitXor => "integer_bit_xor"
  | .integerConvert => "integer_convert"
  | .enumTag => "enum_tag"
  | .blobLength => "blob_length"
  | .blobConcat => "blob_concat"
  | .blobSlice => "blob_slice"
  | .blobCompare => "blob_compare"
  | .blobByte => "blob_byte"
  | .textScalar => "text_scalar"
  | .textInteger => "text_integer"
  | .sequenceSet => "sequence_set"
  | .sequenceTake => "sequence_take"
  | .blobFromByte => "blob_from_byte"
  | .sequencePopLast => "sequence_pop_last"
  | .select => "select"

def opcode : NonemptyCodec Opcode :=
  NonemptyCodec.enumeration opcodeValues
    (by intro value; cases value <;> simp [opcodeValues]) (by decide) (by decide)

def computationType (space : Space) : NonemptyCodec (ComputationType space) :=
  ((NonemptyCodec.reference space .schema).list.pair (((NonemptyCodec.reference space .schema).pair (((NonemptyCodec.reference space .effect).list.pair (((NonemptyCodec.reference space .schema).list.pair ((use.pair ((NonemptyCodec.reference space .regionBinder).list).toCodec)).toCodec)).toCodec)).toCodec)).toCodec).iso
    (fun (v0, v1, v2, v3, v4, v5) => { parameters := v0, result := v1, effects := v2, captureBound := v3, use := v4, regions := v5 })
    (fun value => (value.parameters, value.result, value.effects, value.captureBound, value.use, value.regions))
    (by intro value; cases value; rfl)
    (by intro value; rcases value with ⟨v0, v1, v2, v3, v4, v5⟩; rfl)

def resumptionType (space : Space) : NonemptyCodec (ResumptionType space) :=
  ((NonemptyCodec.reference space .effect).pair (((NonemptyCodec.reference space .schema).pair (((NonemptyCodec.reference space .schema).pair (((NonemptyCodec.reference space .effect).list.pair (((NonemptyCodec.reference space .schema).list.pair (((NonemptyCodec.reference space .effect).list.pair (((NonemptyCodec.reference space .effect).list.pair ((mode.pair ((use.pair (((NonemptyCodec.reference space .regionBinder).list.pair (NonemptyCodec.boolean).toCodec)).toCodec)).toCodec)).toCodec)).toCodec)).toCodec)).toCodec)).toCodec)).toCodec)).toCodec).iso
    (fun (v0, v1, v2, v3, v4, v5, v6, v7, v8, v9, v10) => { effect := v0, input := v1, answer := v2, effects := v3, captureBound := v4, handled := v5, escaping := v6, mode := v7, use := v8, ownedRegions := v9, obligations := v10 })
    (fun value => (value.effect, value.input, value.answer, value.effects, value.captureBound, value.handled, value.escaping, value.mode, value.use, value.ownedRegions, value.obligations))
    (by intro value; cases value; rfl)
    (by intro value; rcases value with ⟨v0, v1, v2, v3, v4, v5, v6, v7, v8, v9, v10⟩; rfl)

inductive InternalTag where
  | computation | capability | cell | region | resumption | suspensionPackage | abstractResource | borrowed
  deriving DecidableEq, Repr

def internalTagValues : List InternalTag := [.computation, .capability, .cell, .region, .resumption, .suspensionPackage, .abstractResource, .borrowed]

def internalTagName : InternalTag → String
  | .computation => "computation"
  | .capability => "capability"
  | .cell => "cell"
  | .region => "region"
  | .resumption => "resumption"
  | .suspensionPackage => "suspension_package"
  | .abstractResource => "abstract_resource"
  | .borrowed => "borrowed"

def internalTag : NonemptyCodec InternalTag :=
  NonemptyCodec.enumeration internalTagValues
    (by intro value; cases value <;> simp [internalTagValues]) (by decide) (by decide)

def internalPayload (space : Space) : InternalTag → Type
  | .computation => ComputationType space
  | .capability => Ref space .effect
  | .cell => (Ref space .schema × Ref space .regionBinder)
  | .region => Ref space .regionBinder
  | .resumption => ResumptionType space
  | .suspensionPackage => Ref space .schema
  | .abstractResource => Ref space .resource
  | .borrowed => (Ref space .schema × Ref space .regionBinder)

def internalView (space : Space) : Internal space → Sigma (internalPayload space)
  | .computation v0 => ⟨.computation, v0⟩
  | .capability v0 => ⟨.capability, v0⟩
  | .cell v0 v1 => ⟨.cell, (v0, v1)⟩
  | .region v0 => ⟨.region, v0⟩
  | .resumption v0 => ⟨.resumption, v0⟩
  | .suspensionPackage v0 => ⟨.suspensionPackage, v0⟩
  | .abstractResource v0 => ⟨.abstractResource, v0⟩
  | .borrowed v0 v1 => ⟨.borrowed, (v0, v1)⟩

def internalOfView (space : Space) : Sigma (internalPayload space) → Internal space
  | ⟨.computation, v0⟩ => .computation v0
  | ⟨.capability, v0⟩ => .capability v0
  | ⟨.cell, (v0, v1)⟩ => .cell v0 v1
  | ⟨.region, v0⟩ => .region v0
  | ⟨.resumption, v0⟩ => .resumption v0
  | ⟨.suspensionPackage, v0⟩ => .suspensionPackage v0
  | ⟨.abstractResource, v0⟩ => .abstractResource v0
  | ⟨.borrowed, (v0, v1)⟩ => .borrowed v0 v1

def internalFields (space : Space) : (tag : InternalTag) → Codec (internalPayload space tag)
  | .computation => ((computationType space)).toCodec
  | .capability => ((NonemptyCodec.reference space .effect)).toCodec
  | .cell => (((NonemptyCodec.reference space .schema).pair ((NonemptyCodec.reference space .regionBinder)).toCodec)).toCodec
  | .region => ((NonemptyCodec.reference space .regionBinder)).toCodec
  | .resumption => ((resumptionType space)).toCodec
  | .suspensionPackage => ((NonemptyCodec.reference space .schema)).toCodec
  | .abstractResource => ((NonemptyCodec.reference space .resource)).toCodec
  | .borrowed => (((NonemptyCodec.reference space .schema).pair ((NonemptyCodec.reference space .regionBinder)).toCodec)).toCodec

def internal (space : Space) : NonemptyCodec (Internal space) :=
  (NonemptyCodec.dependent internalTag (internalFields space)).iso
    (internalOfView space) (internalView space)
    (by intro value; cases value <;> rfl)
    (by rintro ⟨tag, data⟩; cases tag with
      | computation => rfl
      | capability => rfl
      | cell => rcases data with ⟨v0, v1⟩; rfl
      | region => rfl
      | resumption => rfl
      | suspensionPackage => rfl
      | abstractResource => rfl
      | borrowed => rcases data with ⟨v0, v1⟩; rfl
    )

def enumerationTags : NonemptyCodec (List Nat) :=
  (NonemptyCodec.natural.checked fun value => decide (value < 2 ^ 32)).list

inductive SchemaTag where
  | unit | boolean | i8 | i16 | i32 | i64 | u8 | u16 | u32 | u64 | bytes | text | product | sum | seq | vector | internal | array | boundedBytes | boundedText | enumeration
  deriving DecidableEq, Repr

def schemaTagValues : List SchemaTag := [.unit, .boolean, .i8, .i16, .i32, .i64, .u8, .u16, .u32, .u64, .bytes, .text, .product, .sum, .seq, .vector, .internal, .array, .boundedBytes, .boundedText, .enumeration]

def schemaTagName : SchemaTag → String
  | .unit => "unit"
  | .boolean => "boolean"
  | .i8 => "i8"
  | .i16 => "i16"
  | .i32 => "i32"
  | .i64 => "i64"
  | .u8 => "u8"
  | .u16 => "u16"
  | .u32 => "u32"
  | .u64 => "u64"
  | .bytes => "bytes"
  | .text => "text"
  | .product => "product"
  | .sum => "sum"
  | .seq => "seq"
  | .vector => "vector"
  | .internal => "internal"
  | .array => "array"
  | .boundedBytes => "bounded_bytes"
  | .boundedText => "bounded_text"
  | .enumeration => "enumeration"

def schemaTag : NonemptyCodec SchemaTag :=
  NonemptyCodec.enumeration schemaTagValues
    (by intro value; cases value <;> simp [schemaTagValues]) (by decide) (by decide)

def schemaPayload (space : Space) : SchemaTag → Type
  | .unit => Unit
  | .boolean => Unit
  | .i8 => Unit
  | .i16 => Unit
  | .i32 => Unit
  | .i64 => Unit
  | .u8 => Unit
  | .u16 => Unit
  | .u32 => Unit
  | .u64 => Unit
  | .bytes => Unit
  | .text => Unit
  | .product => List (Ref space .schema)
  | .sum => List (Ref space .schema)
  | .seq => Ref space .schema
  | .vector => (Ref space .schema × Nat)
  | .internal => Internal space
  | .array => (Ref space .schema × Nat)
  | .boundedBytes => Nat
  | .boundedText => Nat
  | .enumeration => List Nat

def schemaView (space : Space) : Schema space → Sigma (schemaPayload space)
  | .unit => ⟨.unit, ()⟩
  | .boolean => ⟨.boolean, ()⟩
  | .i8 => ⟨.i8, ()⟩
  | .i16 => ⟨.i16, ()⟩
  | .i32 => ⟨.i32, ()⟩
  | .i64 => ⟨.i64, ()⟩
  | .u8 => ⟨.u8, ()⟩
  | .u16 => ⟨.u16, ()⟩
  | .u32 => ⟨.u32, ()⟩
  | .u64 => ⟨.u64, ()⟩
  | .bytes => ⟨.bytes, ()⟩
  | .text => ⟨.text, ()⟩
  | .product v0 => ⟨.product, v0⟩
  | .sum v0 => ⟨.sum, v0⟩
  | .seq v0 => ⟨.seq, v0⟩
  | .vector v0 v1 => ⟨.vector, (v0, v1)⟩
  | .internal v0 => ⟨.internal, v0⟩
  | .array v0 v1 => ⟨.array, (v0, v1)⟩
  | .boundedBytes v0 => ⟨.boundedBytes, v0⟩
  | .boundedText v0 => ⟨.boundedText, v0⟩
  | .enumeration v0 => ⟨.enumeration, v0⟩

def schemaOfView (space : Space) : Sigma (schemaPayload space) → Schema space
  | ⟨.unit, _⟩ => .unit
  | ⟨.boolean, _⟩ => .boolean
  | ⟨.i8, _⟩ => .i8
  | ⟨.i16, _⟩ => .i16
  | ⟨.i32, _⟩ => .i32
  | ⟨.i64, _⟩ => .i64
  | ⟨.u8, _⟩ => .u8
  | ⟨.u16, _⟩ => .u16
  | ⟨.u32, _⟩ => .u32
  | ⟨.u64, _⟩ => .u64
  | ⟨.bytes, _⟩ => .bytes
  | ⟨.text, _⟩ => .text
  | ⟨.product, v0⟩ => .product v0
  | ⟨.sum, v0⟩ => .sum v0
  | ⟨.seq, v0⟩ => .seq v0
  | ⟨.vector, (v0, v1)⟩ => .vector v0 v1
  | ⟨.internal, v0⟩ => .internal v0
  | ⟨.array, (v0, v1)⟩ => .array v0 v1
  | ⟨.boundedBytes, v0⟩ => .boundedBytes v0
  | ⟨.boundedText, v0⟩ => .boundedText v0
  | ⟨.enumeration, v0⟩ => .enumeration v0

def schemaFields (space : Space) : (tag : SchemaTag) → Codec (schemaPayload space tag)
  | .unit => Codec.unit
  | .boolean => Codec.unit
  | .i8 => Codec.unit
  | .i16 => Codec.unit
  | .i32 => Codec.unit
  | .i64 => Codec.unit
  | .u8 => Codec.unit
  | .u16 => Codec.unit
  | .u32 => Codec.unit
  | .u64 => Codec.unit
  | .bytes => Codec.unit
  | .text => Codec.unit
  | .product => ((NonemptyCodec.reference space .schema).list).toCodec
  | .sum => ((NonemptyCodec.reference space .schema).list).toCodec
  | .seq => ((NonemptyCodec.reference space .schema)).toCodec
  | .vector => (((NonemptyCodec.reference space .schema).pair (NonemptyCodec.natural).toCodec)).toCodec
  | .internal => ((internal space)).toCodec
  | .array => (((NonemptyCodec.reference space .schema).pair (NonemptyCodec.natural).toCodec)).toCodec
  | .boundedBytes => (NonemptyCodec.natural).toCodec
  | .boundedText => (NonemptyCodec.natural).toCodec
  | .enumeration => (enumerationTags).toCodec

def schema (space : Space) : NonemptyCodec (Schema space) :=
  (NonemptyCodec.dependent schemaTag (schemaFields space)).iso
    (schemaOfView space) (schemaView space)
    (by intro value; cases value <;> rfl)
    (by rintro ⟨tag, data⟩; cases tag with
      | unit => cases data; rfl
      | boolean => cases data; rfl
      | i8 => cases data; rfl
      | i16 => cases data; rfl
      | i32 => cases data; rfl
      | i64 => cases data; rfl
      | u8 => cases data; rfl
      | u16 => cases data; rfl
      | u32 => cases data; rfl
      | u64 => cases data; rfl
      | bytes => cases data; rfl
      | text => cases data; rfl
      | product => rfl
      | sum => rfl
      | seq => rfl
      | vector => rcases data with ⟨v0, v1⟩; rfl
      | internal => rfl
      | array => rcases data with ⟨v0, v1⟩; rfl
      | boundedBytes => rfl
      | boundedText => rfl
      | enumeration => rfl
    )

def literal (space : Space) : NonemptyCodec (Literal space) :=
  ((NonemptyCodec.reference space .schema).pair (NonemptyCodec.blob).toCodec).iso
    (fun (v0, v1) => { schema := v0, bytes := v1 })
    (fun value => (value.schema, value.bytes))
    (by intro value; cases value; rfl)
    (by intro value; rcases value with ⟨v0, v1⟩; rfl)

def effect (space : Space) : NonemptyCodec (Effect space) :=
  (NonemptyCodec.blob.pair (((NonemptyCodec.reference space .schema).pair (((NonemptyCodec.reference space .schema).pair (((NonemptyCodec.reference space .effect).list.pair (((NonemptyCodec.reference space .schema).list.pair ((use.pair (NonemptyCodec.boolean).toCodec)).toCodec)).toCodec)).toCodec)).toCodec)).toCodec).iso
    (fun (v0, v1, v2, v3, v4, v5, v6) => { identity := v0, payload := v1, result := v2, useSiteEffects := v3, bodies := v4, controlUse := v5, external := v6 })
    (fun value => (value.identity, value.payload, value.result, value.useSiteEffects, value.bodies, value.controlUse, value.external))
    (by intro value; cases value; rfl)
    (by intro value; rcases value with ⟨v0, v1, v2, v3, v4, v5, v6⟩; rfl)

def instructionFailure (space : Space) : NonemptyCodec (InstructionFailure space) :=
  (fault.pair ((NonemptyCodec.reference space .constant)).toCodec).iso
    (fun (v0, v1) => { kind := v0, value := v1 })
    (fun value => (value.kind, value.value))
    (by intro value; cases value; rfl)
    (by intro value; rcases value with ⟨v0, v1⟩; rfl)

def clause (space : Space) : NonemptyCodec (Clause space) :=
  ((NonemptyCodec.reference space .effect).pair (((NonemptyCodec.reference space .function).pair (((NonemptyCodec.reference space .schema).pair (NonemptyCodec.boolean).toCodec)).toCodec)).toCodec).iso
    (fun (v0, v1, v2, v3) => { effect := v0, function := v1, resumption := v2, direct := v3 })
    (fun value => (value.effect, value.function, value.resumption, value.direct))
    (by intro value; cases value; rfl)
    (by intro value; rcases value with ⟨v0, v1, v2, v3⟩; rfl)

def handler (space : Space) : NonemptyCodec (Handler space) :=
  (mode.pair (((NonemptyCodec.reference space .schema).pair (((NonemptyCodec.reference space .schema).pair (((NonemptyCodec.reference space .function).pair ((((clause space)).list.pair (((NonemptyCodec.optional ((NonemptyCodec.reference space .function)).toCodec).pair (((NonemptyCodec.reference space .schema).list.pair ((NonemptyCodec.reference space .effect).list).toCodec)).toCodec)).toCodec)).toCodec)).toCodec)).toCodec)).toCodec).iso
    (fun (v0, v1, v2, v3, v4, v5, v6, v7) => { mode := v0, input := v1, answer := v2, returnFunction := v3, clauses := v4, forwardFunction := v5, state := v6, effects := v7 })
    (fun value => (value.mode, value.input, value.answer, value.returnFunction, value.clauses, value.forwardFunction, value.state, value.effects))
    (by intro value; cases value; rfl)
    (by intro value; rcases value with ⟨v0, v1, v2, v3, v4, v5, v6, v7⟩; rfl)

def resource (space : Space) : NonemptyCodec (Resource space) :=
  ((NonemptyCodec.reference space .schema).pair (((NonemptyCodec.reference space .function).list.pair ((NonemptyCodec.reference space .function).list).toCodec)).toCodec).iso
    (fun (v0, v1, v2) => { representation := v0, introducers := v1, eliminators := v2 })
    (fun value => (value.representation, value.introducers, value.eliminators))
    (by intro value; cases value; rfl)
    (by intro value; rcases value with ⟨v0, v1, v2⟩; rfl)

def slot : NonemptyCodec (Target.Slot) :=
  NonemptyCodec.natural.iso
    (fun v0 => { value := v0 })
    (fun value => value.value)
    (by intro value; cases value; rfl)
    (by intro value; rfl)

inductive ArgumentTag where
  | slot | returned
  deriving DecidableEq, Repr

def argumentTagValues : List ArgumentTag := [.slot, .returned]

def argumentTagName : ArgumentTag → String
  | .slot => "slot"
  | .returned => "returned"

def argumentTag : NonemptyCodec ArgumentTag :=
  NonemptyCodec.enumeration argumentTagValues
    (by intro value; cases value <;> simp [argumentTagValues]) (by decide) (by decide)

def argumentPayload : ArgumentTag → Type
  | .slot => Target.Slot
  | .returned => Unit

def argumentView : Target.Argument → Sigma (argumentPayload)
  | .slot v0 => ⟨.slot, v0⟩
  | .returned => ⟨.returned, ()⟩

def argumentOfView : Sigma (argumentPayload) → Target.Argument
  | ⟨.slot, v0⟩ => .slot v0
  | ⟨.returned, _⟩ => .returned

def argumentFields : (tag : ArgumentTag) → Codec (argumentPayload tag)
  | .slot => (slot).toCodec
  | .returned => Codec.unit

def argument : NonemptyCodec (Target.Argument) :=
  (NonemptyCodec.dependent argumentTag (argumentFields)).iso
    (argumentOfView) (argumentView)
    (by intro value; cases value <;> rfl)
    (by rintro ⟨tag, data⟩; cases tag with
      | slot => rfl
      | returned => cases data; rfl
    )

def edge : NonemptyCodec (Target.Edge) :=
  ((NonemptyCodec.reference .target .block).pair ((argument).list).toCodec).iso
    (fun (v0, v1) => { block := v0, arguments := v1 })
    (fun value => (value.block, value.arguments))
    (by intro value; cases value; rfl)
    (by intro value; rcases value with ⟨v0, v1⟩; rfl)

def instruction : NonemptyCodec (Target.Instruction) :=
  (opcode.pair (((NonemptyCodec.reference .target .schema).pair (((slot).list.pair ((NonemptyCodec.natural.pair (((instructionFailure .target)).list).toCodec)).toCodec)).toCodec)).toCodec).iso
    (fun (v0, v1, v2, v3, v4) => { opcode := v0, resultType := v1, operands := v2, immediate := v3, failures := v4 })
    (fun value => (value.opcode, value.resultType, value.operands, value.immediate, value.failures))
    (by intro value; cases value; rfl)
    (by intro value; rcases value with ⟨v0, v1, v2, v3, v4⟩; rfl)

def perform : NonemptyCodec (Target.Perform) :=
  ((NonemptyCodec.reference .target .effect).pair (((NonemptyCodec.optional (slot).toCodec).pair ((slot.pair (((slot).list.pair (((slot).list.pair (edge).toCodec)).toCodec)).toCodec)).toCodec)).toCodec).iso
    (fun (v0, v1, v2, v3, v4, v5) => { effect := v0, capability := v1, payload := v2, bodies := v3, useSiteCapabilities := v4, next := v5 })
    (fun value => (value.effect, value.capability, value.payload, value.bodies, value.useSiteCapabilities, value.next))
    (by intro value; cases value; rfl)
    (by intro value; rcases value with ⟨v0, v1, v2, v3, v4, v5⟩; rfl)

inductive TerminatorTag where
  | returnValue | jump | branch | switchVariant | unpackProduct | call | perform | yieldValue | fail | apply | handle | resumeValue | resumeWith | resumeComputation | forward | dispose | protect | withRegion
  deriving DecidableEq, Repr

def terminatorTagValues : List TerminatorTag := [.returnValue, .jump, .branch, .switchVariant, .unpackProduct, .call, .perform, .yieldValue, .fail, .apply, .handle, .resumeValue, .resumeWith, .resumeComputation, .forward, .dispose, .protect, .withRegion]

def terminatorTagName : TerminatorTag → String
  | .returnValue => "return_value"
  | .jump => "jump"
  | .branch => "branch"
  | .switchVariant => "switch_variant"
  | .unpackProduct => "unpack_product"
  | .call => "call"
  | .perform => "perform"
  | .yieldValue => "yield_value"
  | .fail => "fail"
  | .apply => "apply"
  | .handle => "handle"
  | .resumeValue => "resume_value"
  | .resumeWith => "resume_with"
  | .resumeComputation => "resume_computation"
  | .forward => "forward"
  | .dispose => "dispose"
  | .protect => "protect"
  | .withRegion => "with_region"

def terminatorTag : NonemptyCodec TerminatorTag :=
  NonemptyCodec.enumeration terminatorTagValues
    (by intro value; cases value <;> simp [terminatorTagValues]) (by decide) (by decide)

def terminatorPayload : TerminatorTag → Type
  | .returnValue => Target.Slot
  | .jump => Target.Edge
  | .branch => (Target.Slot × Target.Edge × Target.Edge)
  | .switchVariant => (Target.Slot × List Target.Edge)
  | .unpackProduct => (Target.Slot × Ref .target .block × List Target.Slot)
  | .call => (Ref .target .function × List Target.Slot × Target.Edge)
  | .perform => Target.Perform
  | .yieldValue => Target.Edge
  | .fail => Target.Slot
  | .apply => (Target.Slot × List Target.Slot × Target.Edge)
  | .handle => (Ref .target .handler × Target.Slot × List Target.Slot × List Target.Slot × Target.Edge)
  | .resumeValue => (Target.Slot × Target.Slot × Target.Edge)
  | .resumeWith => (Target.Slot × Target.Slot × Ref .target .handler × List Target.Slot × Target.Edge)
  | .resumeComputation => (Target.Slot × Target.Slot × Target.Edge)
  | .forward => Target.Perform
  | .dispose => (Target.Slot × Target.Edge)
  | .protect => (Target.Slot × Target.Slot × List Target.Slot × Option Target.Slot × Option (Ref .target .regionBinder) × Target.Edge)
  | .withRegion => (Ref .target .regionBinder × Target.Slot × List Target.Slot × Target.Edge)

def terminatorView : Target.Terminator → Sigma (terminatorPayload)
  | .returnValue v0 => ⟨.returnValue, v0⟩
  | .jump v0 => ⟨.jump, v0⟩
  | .branch v0 v1 v2 => ⟨.branch, (v0, v1, v2)⟩
  | .switchVariant v0 v1 => ⟨.switchVariant, (v0, v1)⟩
  | .unpackProduct v0 v1 v2 => ⟨.unpackProduct, (v0, v1, v2)⟩
  | .call v0 v1 v2 => ⟨.call, (v0, v1, v2)⟩
  | .perform v0 => ⟨.perform, v0⟩
  | .yieldValue v0 => ⟨.yieldValue, v0⟩
  | .fail v0 => ⟨.fail, v0⟩
  | .apply v0 v1 v2 => ⟨.apply, (v0, v1, v2)⟩
  | .handle v0 v1 v2 v3 v4 => ⟨.handle, (v0, v1, v2, v3, v4)⟩
  | .resumeValue v0 v1 v2 => ⟨.resumeValue, (v0, v1, v2)⟩
  | .resumeWith v0 v1 v2 v3 v4 => ⟨.resumeWith, (v0, v1, v2, v3, v4)⟩
  | .resumeComputation v0 v1 v2 => ⟨.resumeComputation, (v0, v1, v2)⟩
  | .forward v0 => ⟨.forward, v0⟩
  | .dispose v0 v1 => ⟨.dispose, (v0, v1)⟩
  | .protect v0 v1 v2 v3 v4 v5 => ⟨.protect, (v0, v1, v2, v3, v4, v5)⟩
  | .withRegion v0 v1 v2 v3 => ⟨.withRegion, (v0, v1, v2, v3)⟩

def terminatorOfView : Sigma (terminatorPayload) → Target.Terminator
  | ⟨.returnValue, v0⟩ => .returnValue v0
  | ⟨.jump, v0⟩ => .jump v0
  | ⟨.branch, (v0, v1, v2)⟩ => .branch v0 v1 v2
  | ⟨.switchVariant, (v0, v1)⟩ => .switchVariant v0 v1
  | ⟨.unpackProduct, (v0, v1, v2)⟩ => .unpackProduct v0 v1 v2
  | ⟨.call, (v0, v1, v2)⟩ => .call v0 v1 v2
  | ⟨.perform, v0⟩ => .perform v0
  | ⟨.yieldValue, v0⟩ => .yieldValue v0
  | ⟨.fail, v0⟩ => .fail v0
  | ⟨.apply, (v0, v1, v2)⟩ => .apply v0 v1 v2
  | ⟨.handle, (v0, v1, v2, v3, v4)⟩ => .handle v0 v1 v2 v3 v4
  | ⟨.resumeValue, (v0, v1, v2)⟩ => .resumeValue v0 v1 v2
  | ⟨.resumeWith, (v0, v1, v2, v3, v4)⟩ => .resumeWith v0 v1 v2 v3 v4
  | ⟨.resumeComputation, (v0, v1, v2)⟩ => .resumeComputation v0 v1 v2
  | ⟨.forward, v0⟩ => .forward v0
  | ⟨.dispose, (v0, v1)⟩ => .dispose v0 v1
  | ⟨.protect, (v0, v1, v2, v3, v4, v5)⟩ => .protect v0 v1 v2 v3 v4 v5
  | ⟨.withRegion, (v0, v1, v2, v3)⟩ => .withRegion v0 v1 v2 v3

def terminatorFields : (tag : TerminatorTag) → Codec (terminatorPayload tag)
  | .returnValue => (slot).toCodec
  | .jump => (edge).toCodec
  | .branch => ((slot.pair ((edge.pair (edge).toCodec)).toCodec)).toCodec
  | .switchVariant => ((slot.pair ((edge).list).toCodec)).toCodec
  | .unpackProduct => ((slot.pair (((NonemptyCodec.reference .target .block).pair ((slot).list).toCodec)).toCodec)).toCodec
  | .call => (((NonemptyCodec.reference .target .function).pair (((slot).list.pair (edge).toCodec)).toCodec)).toCodec
  | .perform => (perform).toCodec
  | .yieldValue => (edge).toCodec
  | .fail => (slot).toCodec
  | .apply => ((slot.pair (((slot).list.pair (edge).toCodec)).toCodec)).toCodec
  | .handle => (((NonemptyCodec.reference .target .handler).pair ((slot.pair (((slot).list.pair (((slot).list.pair (edge).toCodec)).toCodec)).toCodec)).toCodec)).toCodec
  | .resumeValue => ((slot.pair ((slot.pair (edge).toCodec)).toCodec)).toCodec
  | .resumeWith => ((slot.pair ((slot.pair (((NonemptyCodec.reference .target .handler).pair (((slot).list.pair (edge).toCodec)).toCodec)).toCodec)).toCodec)).toCodec
  | .resumeComputation => ((slot.pair ((slot.pair (edge).toCodec)).toCodec)).toCodec
  | .forward => (perform).toCodec
  | .dispose => ((slot.pair (edge).toCodec)).toCodec
  | .protect => ((slot.pair ((slot.pair (((slot).list.pair (((NonemptyCodec.optional (slot).toCodec).pair (((NonemptyCodec.optional ((NonemptyCodec.reference .target .regionBinder)).toCodec).pair (edge).toCodec)).toCodec)).toCodec)).toCodec)).toCodec)).toCodec
  | .withRegion => (((NonemptyCodec.reference .target .regionBinder).pair ((slot.pair (((slot).list.pair (edge).toCodec)).toCodec)).toCodec)).toCodec

def terminator : NonemptyCodec (Target.Terminator) :=
  (NonemptyCodec.dependent terminatorTag (terminatorFields)).iso
    (terminatorOfView) (terminatorView)
    (by intro value; cases value <;> rfl)
    (by rintro ⟨tag, data⟩; cases tag with
      | returnValue => rfl
      | jump => rfl
      | branch => rcases data with ⟨v0, v1, v2⟩; rfl
      | switchVariant => rcases data with ⟨v0, v1⟩; rfl
      | unpackProduct => rcases data with ⟨v0, v1, v2⟩; rfl
      | call => rcases data with ⟨v0, v1, v2⟩; rfl
      | perform => rfl
      | yieldValue => rfl
      | fail => rfl
      | apply => rcases data with ⟨v0, v1, v2⟩; rfl
      | handle => rcases data with ⟨v0, v1, v2, v3, v4⟩; rfl
      | resumeValue => rcases data with ⟨v0, v1, v2⟩; rfl
      | resumeWith => rcases data with ⟨v0, v1, v2, v3, v4⟩; rfl
      | resumeComputation => rcases data with ⟨v0, v1, v2⟩; rfl
      | forward => rfl
      | dispose => rcases data with ⟨v0, v1⟩; rfl
      | protect => rcases data with ⟨v0, v1, v2, v3, v4, v5⟩; rfl
      | withRegion => rcases data with ⟨v0, v1, v2, v3⟩; rfl
    )

def block : NonemptyCodec (Target.Block) :=
  ((NonemptyCodec.reference .target .function).pair (((NonemptyCodec.reference .target .schema).list.pair (((instruction).list.pair (terminator).toCodec)).toCodec)).toCodec).iso
    (fun (v0, v1, v2, v3) => { function := v0, parameters := v1, instructions := v2, terminator := v3 })
    (fun value => (value.function, value.parameters, value.instructions, value.terminator))
    (by intro value; cases value; rfl)
    (by intro value; rcases value with ⟨v0, v1, v2, v3⟩; rfl)

def function : NonemptyCodec (Target.Function) :=
  ((NonemptyCodec.reference .target .block).pair (((NonemptyCodec.reference .target .schema).list.pair (((NonemptyCodec.reference .target .schema).pair (((NonemptyCodec.reference .target .effect).list.pair ((NonemptyCodec.reference .target .regionBinder).list).toCodec)).toCodec)).toCodec)).toCodec).iso
    (fun (v0, v1, v2, v3, v4) => { entry := v0, parameters := v1, result := v2, effects := v3, regions := v4 })
    (fun value => (value.entry, value.parameters, value.result, value.effects, value.regions))
    (by intro value; cases value; rfl)
    (by intro value; rcases value with ⟨v0, v1, v2, v3, v4⟩; rfl)

def capture : NonemptyCodec (Target.Capture) :=
  ((NonemptyCodec.reference .target .schema).list.pair (((NonemptyCodec.reference .target .regionBinder).list.pair (((NonemptyCodec.reference .target .regionBinder).list.pair (use).toCodec)).toCodec)).toCodec).iso
    (fun (v0, v1, v2, v3) => { fields := v0, ownedRegions := v1, borrowedRegions := v2, use := v3 })
    (fun value => (value.fields, value.ownedRegions, value.borrowedRegions, value.use))
    (by intro value; cases value; rfl)
    (by intro value; rcases value with ⟨v0, v1, v2, v3⟩; rfl)

def constructor : NonemptyCodec (Target.Constructor) :=
  ((NonemptyCodec.reference .target .function).pair (((NonemptyCodec.reference .target .capture).pair ((NonemptyCodec.reference .target .schema)).toCodec)).toCodec).iso
    (fun (v0, v1, v2) => { function := v0, capture := v1, schema := v2 })
    (fun value => (value.function, value.capture, value.schema))
    (by intro value; cases value; rfl)
    (by intro value; rcases value with ⟨v0, v1, v2⟩; rfl)

def scopeCatalog : NonemptyCodec (Target.ScopeCatalog) :=
  ((capture).list.pair ((NonemptyCodec.natural.pair (((resource .target)).list).toCodec)).toCodec).iso
    (fun (v0, v1, v2) => { captures := v0, regionCount := v1, resources := v2 })
    (fun value => (value.captures, value.regionCount, value.resources))
    (by intro value; cases value; rfl)
    (by intro value; rcases value with ⟨v0, v1, v2⟩; rfl)

def programRoots : NonemptyCodec (Target.Roots) :=
  (NonemptyCodec.natural.pair (((NonemptyCodec.reference .target .function).pair (((NonemptyCodec.reference .target .schema).pair ((NonemptyCodec.reference .target .schema)).toCodec)).toCodec)).toCodec).iso
    (fun (v0, v1, v2, v3) => { profile := v0, entry := v1, result := v2, failure := v3 })
    (fun value => (value.profile, value.entry, value.result, value.failure))
    (by intro value; cases value; rfl)
    (by intro value; rcases value with ⟨v0, v1, v2, v3⟩; rfl)

def rawProgram : NonemptyCodec (Target.Program) :=
  (programRoots.pair ((((schema .target)).list.pair ((((literal .target)).list.pair ((((effect .target)).list.pair (((function).list.pair (((block).list.pair ((((handler .target)).list.pair ((scopeCatalog.pair ((constructor).list).toCodec)).toCodec)).toCodec)).toCodec)).toCodec)).toCodec)).toCodec)).toCodec).iso
    (fun (v0, v1, v2, v3, v4, v5, v6, v7, v8) => { roots := v0, schemas := v1, constants := v2, effects := v3, functions := v4, blocks := v5, handlers := v6, scopes := v7, constructors := v8 })
    (fun value => (value.roots, value.schemas, value.constants, value.effects, value.functions, value.blocks, value.handlers, value.scopes, value.constructors))
    (by intro value; cases value; rfl)
    (by intro value; rcases value with ⟨v0, v1, v2, v3, v4, v5, v6, v7, v8⟩; rfl)

inductive ReasonTag where
  | text | bytes
  deriving DecidableEq, Repr

def reasonTagValues : List ReasonTag := [.text, .bytes]

def reasonTagName : ReasonTag → String
  | .text => "text"
  | .bytes => "bytes"

def reasonTag : NonemptyCodec ReasonTag :=
  NonemptyCodec.enumeration reasonTagValues
    (by intro value; cases value <;> simp [reasonTagValues]) (by decide) (by decide)

def reasonPayload : ReasonTag → Type
  | .text => Bytes
  | .bytes => Bytes

def reasonView : Protocol.Reason → Sigma (reasonPayload)
  | .text v0 => ⟨.text, v0⟩
  | .bytes v0 => ⟨.bytes, v0⟩

def reasonOfView : Sigma (reasonPayload) → Protocol.Reason
  | ⟨.text, v0⟩ => .text v0
  | ⟨.bytes, v0⟩ => .bytes v0

def reasonFields : (tag : ReasonTag) → Codec (reasonPayload tag)
  | .text => (NonemptyCodec.blob).toCodec
  | .bytes => (NonemptyCodec.blob).toCodec

def reason : NonemptyCodec (Protocol.Reason) :=
  (NonemptyCodec.dependent reasonTag (reasonFields)).iso
    (reasonOfView) (reasonView)
    (by intro value; cases value <;> rfl)
    (by rintro ⟨tag, data⟩; cases tag with
      | text => rfl
      | bytes => rfl
    )

def invocationModeValues : List Protocol.Mode := [.advance, .run]

def invocationModeName : Protocol.Mode → String
  | .advance => "advance"
  | .run => "run"

def invocationMode : NonemptyCodec Protocol.Mode :=
  NonemptyCodec.enumeration invocationModeValues
    (by intro value; cases value <;> simp [invocationModeValues]) (by decide) (by decide)

inductive InstanceDataTag where
  | initialArgs | state
  deriving DecidableEq, Repr

def instanceDataTagValues : List InstanceDataTag := [.initialArgs, .state]

def instanceDataTagName : InstanceDataTag → String
  | .initialArgs => "initial_args"
  | .state => "state"

def instanceDataTag : NonemptyCodec InstanceDataTag :=
  NonemptyCodec.enumeration instanceDataTagValues
    (by intro value; cases value <;> simp [instanceDataTagValues]) (by decide) (by decide)

def instanceDataPayload : InstanceDataTag → Type
  | .initialArgs => Bytes
  | .state => Bytes

def instanceDataView : Protocol.Instance → Sigma (instanceDataPayload)
  | .initialArgs v0 => ⟨.initialArgs, v0⟩
  | .state v0 => ⟨.state, v0⟩

def instanceDataOfView : Sigma (instanceDataPayload) → Protocol.Instance
  | ⟨.initialArgs, v0⟩ => .initialArgs v0
  | ⟨.state, v0⟩ => .state v0

def instanceDataFields : (tag : InstanceDataTag) → Codec (instanceDataPayload tag)
  | .initialArgs => (NonemptyCodec.blob).toCodec
  | .state => (NonemptyCodec.blob).toCodec

def instanceData : NonemptyCodec (Protocol.Instance) :=
  (NonemptyCodec.dependent instanceDataTag (instanceDataFields)).iso
    (instanceDataOfView) (instanceDataView)
    (by intro value; cases value <;> rfl)
    (by rintro ⟨tag, data⟩; cases tag with
      | initialArgs => rfl
      | state => rfl
    )

inductive ExternalControlTag where
  | continueValue | cancel
  deriving DecidableEq, Repr

def externalControlTagValues : List ExternalControlTag := [.continueValue, .cancel]

def externalControlTagName : ExternalControlTag → String
  | .continueValue => "continue_value"
  | .cancel => "cancel"

def externalControlTag : NonemptyCodec ExternalControlTag :=
  NonemptyCodec.enumeration externalControlTagValues
    (by intro value; cases value <;> simp [externalControlTagValues]) (by decide) (by decide)

def externalControlPayload : ExternalControlTag → Type
  | .continueValue => Option Bytes
  | .cancel => Protocol.Reason

def externalControlView : Protocol.Control → Sigma (externalControlPayload)
  | .continueValue v0 => ⟨.continueValue, v0⟩
  | .cancel v0 => ⟨.cancel, v0⟩

def externalControlOfView : Sigma (externalControlPayload) → Protocol.Control
  | ⟨.continueValue, v0⟩ => .continueValue v0
  | ⟨.cancel, v0⟩ => .cancel v0

def externalControlFields : (tag : ExternalControlTag) → Codec (externalControlPayload tag)
  | .continueValue => ((NonemptyCodec.optional (NonemptyCodec.blob).toCodec)).toCodec
  | .cancel => (reason).toCodec

def externalControl : NonemptyCodec (Protocol.Control) :=
  (NonemptyCodec.dependent externalControlTag (externalControlFields)).iso
    (externalControlOfView) (externalControlView)
    (by intro value; cases value <;> rfl)
    (by rintro ⟨tag, data⟩; cases tag with
      | continueValue => rfl
      | cancel => rfl
    )

def rawInput : NonemptyCodec (Protocol.Input) :=
  (invocationMode.pair ((NonemptyCodec.blob.pair ((instanceData.pair (externalControl).toCodec)).toCodec)).toCodec).iso
    (fun (v0, v1, v2, v3) => { mode := v0, image := v1, instanceData := v2, control := v3 })
    (fun value => (value.mode, value.image, value.instanceData, value.control))
    (by intro value; cases value; rfl)
    (by intro value; rcases value with ⟨v0, v1, v2, v3⟩; rfl)

def provenanceValues : List Protocol.Provenance := [.notObserved, .exact, .lowerBound]

def provenanceName : Protocol.Provenance → String
  | .notObserved => "not_observed"
  | .exact => "exact"
  | .lowerBound => "lower_bound"

def provenance : NonemptyCodec Protocol.Provenance :=
  NonemptyCodec.enumeration provenanceValues
    (by intro value; cases value <;> simp [provenanceValues]) (by decide) (by decide)

def arenaValues : List Protocol.Arena := [.input, .working, .output, .memory]

def arenaName : Protocol.Arena → String
  | .input => "input"
  | .working => "working"
  | .output => "output"
  | .memory => "memory"

def arena : NonemptyCodec Protocol.Arena :=
  NonemptyCodec.enumeration arenaValues
    (by intro value; cases value <;> simp [arenaValues]) (by decide) (by decide)

def bound : NonemptyCodec (Protocol.Bound) :=
  (NonemptyCodec.natural.pair (provenance).toCodec).iso
    (fun (v0, v1) => { amount := v0, provenance := v1 })
    (fun value => (value.amount, value.provenance))
    (by intro value; cases value; rfl)
    (by intro value; rcases value with ⟨v0, v1⟩; rfl)

def capacity : NonemptyCodec (Protocol.Capacity) :=
  (arena.pair ((bound.pair ((bound.pair ((bound.pair (bound).toCodec)).toCodec)).toCodec)).toCodec).iso
    (fun (v0, v1, v2, v3, v4) => { arena := v0, input := v1, working := v2, output := v3, memoryPages := v4 })
    (fun value => (value.arena, value.input, value.working, value.output, value.memoryPages))
    (by intro value; cases value; rfl)
    (by intro value; rcases value with ⟨v0, v1, v2, v3, v4⟩; rfl)

inductive RawOutcomeTag where
  | progressed | requested | yielded | completed | failed | cancelled | needsCapacity
  deriving DecidableEq, Repr

def rawOutcomeTagValues : List RawOutcomeTag := [.progressed, .requested, .yielded, .completed, .failed, .cancelled, .needsCapacity]

def rawOutcomeTagName : RawOutcomeTag → String
  | .progressed => "progressed"
  | .requested => "requested"
  | .yielded => "yielded"
  | .completed => "completed"
  | .failed => "failed"
  | .cancelled => "cancelled"
  | .needsCapacity => "needs_capacity"

def rawOutcomeTag : NonemptyCodec RawOutcomeTag :=
  NonemptyCodec.enumeration rawOutcomeTagValues
    (by intro value; cases value <;> simp [rawOutcomeTagValues]) (by decide) (by decide)

def rawOutcomePayload : RawOutcomeTag → Type
  | .progressed => Bytes
  | .requested => (Bytes × Bytes)
  | .yielded => Bytes
  | .completed => Bytes
  | .failed => (Bytes × Bytes × Option Protocol.Reason)
  | .cancelled => (Protocol.Reason × Bytes)
  | .needsCapacity => Protocol.Capacity

def rawOutcomeView : Protocol.Outcome → Sigma (rawOutcomePayload)
  | .progressed v0 => ⟨.progressed, v0⟩
  | .requested v0 v1 => ⟨.requested, (v0, v1)⟩
  | .yielded v0 => ⟨.yielded, v0⟩
  | .completed v0 => ⟨.completed, v0⟩
  | .failed v0 v1 v2 => ⟨.failed, (v0, v1, v2)⟩
  | .cancelled v0 v1 => ⟨.cancelled, (v0, v1)⟩
  | .needsCapacity v0 => ⟨.needsCapacity, v0⟩

def rawOutcomeOfView : Sigma (rawOutcomePayload) → Protocol.Outcome
  | ⟨.progressed, v0⟩ => .progressed v0
  | ⟨.requested, (v0, v1)⟩ => .requested v0 v1
  | ⟨.yielded, v0⟩ => .yielded v0
  | ⟨.completed, v0⟩ => .completed v0
  | ⟨.failed, (v0, v1, v2)⟩ => .failed v0 v1 v2
  | ⟨.cancelled, (v0, v1)⟩ => .cancelled v0 v1
  | ⟨.needsCapacity, v0⟩ => .needsCapacity v0

def rawOutcomeFields : (tag : RawOutcomeTag) → Codec (rawOutcomePayload tag)
  | .progressed => (NonemptyCodec.blob).toCodec
  | .requested => ((NonemptyCodec.blob.pair (NonemptyCodec.blob).toCodec)).toCodec
  | .yielded => (NonemptyCodec.blob).toCodec
  | .completed => (NonemptyCodec.blob).toCodec
  | .failed => ((NonemptyCodec.blob.pair ((NonemptyCodec.blob.pair ((NonemptyCodec.optional (reason).toCodec)).toCodec)).toCodec)).toCodec
  | .cancelled => ((reason.pair (NonemptyCodec.blob).toCodec)).toCodec
  | .needsCapacity => (capacity).toCodec

def rawOutcome : NonemptyCodec (Protocol.Outcome) :=
  (NonemptyCodec.dependent rawOutcomeTag (rawOutcomeFields)).iso
    (rawOutcomeOfView) (rawOutcomeView)
    (by intro value; cases value <;> rfl)
    (by rintro ⟨tag, data⟩; cases tag with
      | progressed => rfl
      | requested => rcases data with ⟨v0, v1⟩; rfl
      | yielded => rfl
      | completed => rfl
      | failed => rcases data with ⟨v0, v1, v2⟩; rfl
      | cancelled => rcases data with ⟨v0, v1⟩; rfl
      | needsCapacity => rfl
    )

def rawRequest : NonemptyCodec (Protocol.Request) :=
  ((NonemptyCodec.fixedBytes 32 (by decide)).pair (((NonemptyCodec.fixedBytes 32 (by decide)).pair (((NonemptyCodec.fixedBytes 32 (by decide)).pair (((NonemptyCodec.fixedBytes 32 (by decide)).pair ((NonemptyCodec.blob.pair ((NonemptyCodec.blob.pair ((NonemptyCodec.blob.pair ((NonemptyCodec.blob.pair ((NonemptyCodec.fixedBytes 32 (by decide))).toCodec)).toCodec)).toCodec)).toCodec)).toCodec)).toCodec)).toCodec)).toCodec).iso
    (fun (v0, v1, v2, v3, v4, v5, v6, v7, v8) => { programIdentity := v0, pendingStateDigest := v1, residualContractDigest := v2, continuationBindingDigest := v3, semanticIdentity := v4, payloadSchema := v5, resumeSchema := v6, payload := v7, requestIdentity := v8 })
    (fun value => (value.programIdentity, value.pendingStateDigest, value.residualContractDigest, value.continuationBindingDigest, value.semanticIdentity, value.payloadSchema, value.resumeSchema, value.payload, value.requestIdentity))
    (by intro value; cases value; rfl)
    (by intro value; rcases value with ⟨v0, v1, v2, v3, v4, v5, v6, v7, v8⟩; rfl)

def rawResult : NonemptyCodec (Protocol.Result) :=
  ((NonemptyCodec.fixedBytes 32 (by decide)).pair (((NonemptyCodec.fixedBytes 32 (by decide)).pair (NonemptyCodec.blob).toCodec)).toCodec).iso
    (fun (v0, v1, v2) => { requestIdentity := v0, resumeSchemaDigest := v1, value := v2 })
    (fun value => (value.requestIdentity, value.resumeSchemaDigest, value.value))
    (by intro value; cases value; rfl)
    (by intro value; rcases value with ⟨v0, v1, v2⟩; rfl)

def ownedRef : NonemptyCodec (Graph.OwnedRef) :=
  (NonemptyCodec.reference .runtime .node).iso
    (fun v0 => { node := v0 })
    (fun value => value.node)
    (by intro value; cases value; rfl)
    (by intro value; rfl)

inductive ValueBodyTag where
  | scalar | blob | reference | owned
  deriving DecidableEq, Repr

def valueBodyTagValues : List ValueBodyTag := [.scalar, .blob, .reference, .owned]

def valueBodyTagName : ValueBodyTag → String
  | .scalar => "scalar"
  | .blob => "blob"
  | .reference => "reference"
  | .owned => "owned"

def valueBodyTag : NonemptyCodec ValueBodyTag :=
  NonemptyCodec.enumeration valueBodyTagValues
    (by intro value; cases value <;> simp [valueBodyTagValues]) (by decide) (by decide)

def valueBodyPayload : ValueBodyTag → Type
  | .scalar => Vector UInt8 8
  | .blob => BlobId
  | .reference => NodeId
  | .owned => Graph.OwnedRef

def valueBodyView : Graph.ValueBody → Sigma (valueBodyPayload)
  | .scalar v0 => ⟨.scalar, v0⟩
  | .blob v0 => ⟨.blob, v0⟩
  | .reference v0 => ⟨.reference, v0⟩
  | .owned v0 => ⟨.owned, v0⟩

def valueBodyOfView : Sigma (valueBodyPayload) → Graph.ValueBody
  | ⟨.scalar, v0⟩ => .scalar v0
  | ⟨.blob, v0⟩ => .blob v0
  | ⟨.reference, v0⟩ => .reference v0
  | ⟨.owned, v0⟩ => .owned v0

def valueBodyFields : (tag : ValueBodyTag) → Codec (valueBodyPayload tag)
  | .scalar => ((NonemptyCodec.fixedBytes 8 (by decide))).toCodec
  | .blob => ((NonemptyCodec.reference .runtime .blob)).toCodec
  | .reference => ((NonemptyCodec.reference .runtime .node)).toCodec
  | .owned => (ownedRef).toCodec

def valueBody : NonemptyCodec (Graph.ValueBody) :=
  (NonemptyCodec.dependent valueBodyTag (valueBodyFields)).iso
    (valueBodyOfView) (valueBodyView)
    (by intro value; cases value <;> rfl)
    (by rintro ⟨tag, data⟩; cases tag with
      | scalar => rfl
      | blob => rfl
      | reference => rfl
      | owned => rfl
    )

def value : NonemptyCodec (Graph.Value) :=
  ((NonemptyCodec.reference .target .schema).pair (valueBody).toCodec).iso
    (fun (v0, v1) => { schema := v0, body := v1 })
    (fun value => (value.schema, value.body))
    (by intro value; cases value; rfl)
    (by intro value; rcases value with ⟨v0, v1⟩; rfl)

def graphBlob : NonemptyCodec (Graph.Blob) :=
  ((NonemptyCodec.reference .target .schema).pair (NonemptyCodec.blob).toCodec).iso
    (fun (v0, v1) => { schema := v0, bytes := v1 })
    (fun value => (value.schema, value.bytes))
    (by intro value; cases value; rfl)
    (by intro value; rcases value with ⟨v0, v1⟩; rfl)

def control : NonemptyCodec (Graph.Control) :=
  ((NonemptyCodec.reference .target .block).pair (((value).list.pair (((NonemptyCodec.optional ((NonemptyCodec.reference .runtime .node)).toCodec).pair (((NonemptyCodec.optional ((NonemptyCodec.reference .runtime .node)).toCodec).pair ((NonemptyCodec.optional ((NonemptyCodec.reference .runtime .node)).toCodec)).toCodec)).toCodec)).toCodec)).toCodec).iso
    (fun (v0, v1, v2, v3, v4) => { block := v0, arguments := v1, parent := v2, evidence := v3, region := v4 })
    (fun value => (value.block, value.arguments, value.parent, value.evidence, value.region))
    (by intro value; cases value; rfl)
    (by intro value; rcases value with ⟨v0, v1, v2, v3, v4⟩; rfl)

def continuation : NonemptyCodec (Graph.Continuation) :=
  ((NonemptyCodec.reference .target .block).pair ((((NonemptyCodec.optional (value).toCodec)).list.pair (((NonemptyCodec.optional ((NonemptyCodec.reference .runtime .node)).toCodec).pair (((NonemptyCodec.optional ((NonemptyCodec.reference .runtime .node)).toCodec).pair ((NonemptyCodec.optional ((NonemptyCodec.reference .runtime .node)).toCodec)).toCodec)).toCodec)).toCodec)).toCodec).iso
    (fun (v0, v1, v2, v3, v4) => { sourceBlock := v0, arguments := v1, parent := v2, evidence := v3, region := v4 })
    (fun value => (value.sourceBlock, value.arguments, value.parent, value.evidence, value.region))
    (by intro value; cases value; rfl)
    (by intro value; rcases value with ⟨v0, v1, v2, v3, v4⟩; rfl)

inductive ExitReasonTag where
  | normal | failure | cancellation | abandoned
  deriving DecidableEq, Repr

def exitReasonTagValues : List ExitReasonTag := [.normal, .failure, .cancellation, .abandoned]

def exitReasonTagName : ExitReasonTag → String
  | .normal => "normal"
  | .failure => "failure"
  | .cancellation => "cancellation"
  | .abandoned => "abandoned"

def exitReasonTag : NonemptyCodec ExitReasonTag :=
  NonemptyCodec.enumeration exitReasonTagValues
    (by intro value; cases value <;> simp [exitReasonTagValues]) (by decide) (by decide)

def exitReasonPayload : ExitReasonTag → Type
  | .normal => Graph.Value
  | .failure => Graph.Value
  | .cancellation => Unit
  | .abandoned => Unit

def exitReasonView : Graph.ExitReason → Sigma (exitReasonPayload)
  | .normal v0 => ⟨.normal, v0⟩
  | .failure v0 => ⟨.failure, v0⟩
  | .cancellation => ⟨.cancellation, ()⟩
  | .abandoned => ⟨.abandoned, ()⟩

def exitReasonOfView : Sigma (exitReasonPayload) → Graph.ExitReason
  | ⟨.normal, v0⟩ => .normal v0
  | ⟨.failure, v0⟩ => .failure v0
  | ⟨.cancellation, _⟩ => .cancellation
  | ⟨.abandoned, _⟩ => .abandoned

def exitReasonFields : (tag : ExitReasonTag) → Codec (exitReasonPayload tag)
  | .normal => (value).toCodec
  | .failure => (value).toCodec
  | .cancellation => Codec.unit
  | .abandoned => Codec.unit

def exitReason : NonemptyCodec (Graph.ExitReason) :=
  (NonemptyCodec.dependent exitReasonTag (exitReasonFields)).iso
    (exitReasonOfView) (exitReasonView)
    (by intro value; cases value <;> rfl)
    (by rintro ⟨tag, data⟩; cases tag with
      | normal => rfl
      | failure => rfl
      | cancellation => cases data; rfl
      | abandoned => cases data; rfl
    )

def exit : NonemptyCodec (Graph.Exit) :=
  (exitReason.pair (((value).list.pair (((NonemptyCodec.optional (reason).toCodec).pair (((NonemptyCodec.optional ((NonemptyCodec.reference .runtime .node)).toCodec).pair (((NonemptyCodec.optional ((NonemptyCodec.reference .runtime .node)).toCodec).pair ((value).list).toCodec)).toCodec)).toCodec)).toCodec)).toCodec).iso
    (fun (v0, v1, v2, v3, v4, v5) => { reason := v0, cleanupFailures := v1, cancellation := v2, stop := v3, outer := v4, discarded := v5 })
    (fun value => (value.reason, value.cleanupFailures, value.cancellation, value.stop, value.outer, value.discarded))
    (by intro value; cases value; rfl)
    (by intro value; rcases value with ⟨v0, v1, v2, v3, v4, v5⟩; rfl)

def captureState : NonemptyCodec (Graph.Capture) :=
  ((NonemptyCodec.reference .target .schema).pair (((NonemptyCodec.optional ((NonemptyCodec.reference .runtime .node)).toCodec).pair (((NonemptyCodec.reference .runtime .node).pair (((NonemptyCodec.optional ((NonemptyCodec.reference .runtime .node)).toCodec).pair ((value).list).toCodec)).toCodec)).toCodec)).toCodec).iso
    (fun (v0, v1, v2, v3, v4) => { schema := v0, capture := v1, delimiter := v2, evidence := v3, useSiteCapabilities := v4 })
    (fun value => (value.schema, value.capture, value.delimiter, value.evidence, value.useSiteCapabilities))
    (by intro value; cases value; rfl)
    (by intro value; rcases value with ⟨v0, v1, v2, v3, v4⟩; rfl)

def attachmentPhaseValues : List Graph.AttachmentPhase := [.active, .suspended]

def attachmentPhaseName : Graph.AttachmentPhase → String
  | .active => "active"
  | .suspended => "suspended"

def attachmentPhase : NonemptyCodec Graph.AttachmentPhase :=
  NonemptyCodec.enumeration attachmentPhaseValues
    (by intro value; cases value <;> simp [attachmentPhaseValues]) (by decide) (by decide)

inductive ObligationStatusTag where
  | pending | running | completed | failed
  deriving DecidableEq, Repr

def obligationStatusTagValues : List ObligationStatusTag := [.pending, .running, .completed, .failed]

def obligationStatusTagName : ObligationStatusTag → String
  | .pending => "pending"
  | .running => "running"
  | .completed => "completed"
  | .failed => "failed"

def obligationStatusTag : NonemptyCodec ObligationStatusTag :=
  NonemptyCodec.enumeration obligationStatusTagValues
    (by intro value; cases value <;> simp [obligationStatusTagValues]) (by decide) (by decide)

def obligationStatusPayload : ObligationStatusTag → Type
  | .pending => Unit
  | .running => NodeId
  | .completed => Unit
  | .failed => Graph.Value

def obligationStatusView : Graph.ObligationStatus → Sigma (obligationStatusPayload)
  | .pending => ⟨.pending, ()⟩
  | .running v0 => ⟨.running, v0⟩
  | .completed => ⟨.completed, ()⟩
  | .failed v0 => ⟨.failed, v0⟩

def obligationStatusOfView : Sigma (obligationStatusPayload) → Graph.ObligationStatus
  | ⟨.pending, _⟩ => .pending
  | ⟨.running, v0⟩ => .running v0
  | ⟨.completed, _⟩ => .completed
  | ⟨.failed, v0⟩ => .failed v0

def obligationStatusFields : (tag : ObligationStatusTag) → Codec (obligationStatusPayload tag)
  | .pending => Codec.unit
  | .running => ((NonemptyCodec.reference .runtime .node)).toCodec
  | .completed => Codec.unit
  | .failed => (value).toCodec

def obligationStatus : NonemptyCodec (Graph.ObligationStatus) :=
  (NonemptyCodec.dependent obligationStatusTag (obligationStatusFields)).iso
    (obligationStatusOfView) (obligationStatusView)
    (by intro value; cases value <;> rfl)
    (by rintro ⟨tag, data⟩; cases tag with
      | pending => cases data; rfl
      | running => rfl
      | completed => cases data; rfl
      | failed => rfl
    )

inductive NodeTag where
  | control | continuation | handler | attachment | environment | aggregate | region | regionScope | injection | protection | cleanupReturn | disposalReturn | unwind | cell | oneShot | multiTemplate | branch | package | computation | resource | borrow | obligation | pending | exit
  deriving DecidableEq, Repr

def nodeTagValues : List NodeTag := [.control, .continuation, .handler, .attachment, .environment, .aggregate, .region, .regionScope, .injection, .protection, .cleanupReturn, .disposalReturn, .unwind, .cell, .oneShot, .multiTemplate, .branch, .package, .computation, .resource, .borrow, .obligation, .pending, .exit]

def nodeTagName : NodeTag → String
  | .control => "control"
  | .continuation => "continuation"
  | .handler => "handler"
  | .attachment => "attachment"
  | .environment => "environment"
  | .aggregate => "aggregate"
  | .region => "region"
  | .regionScope => "region_scope"
  | .injection => "injection"
  | .protection => "protection"
  | .cleanupReturn => "cleanup_return"
  | .disposalReturn => "disposal_return"
  | .unwind => "unwind"
  | .cell => "cell"
  | .oneShot => "one_shot"
  | .multiTemplate => "multi_template"
  | .branch => "branch"
  | .package => "package"
  | .computation => "computation"
  | .resource => "resource"
  | .borrow => "borrow"
  | .obligation => "obligation"
  | .pending => "pending"
  | .exit => "exit"

def nodeTag : NonemptyCodec NodeTag :=
  NonemptyCodec.enumeration nodeTagValues
    (by intro value; cases value <;> simp [nodeTagValues]) (by decide) (by decide)

def nodePayload : NodeTag → Type
  | .control => Graph.Control
  | .continuation => Graph.Continuation
  | .handler => (Ref .target .handler × List Graph.Value × Option NodeId × Option NodeId)
  | .attachment => (NodeId × Option NodeId × Option NodeId × Graph.AttachmentPhase × Option NodeId)
  | .environment => (List Graph.Value × Option NodeId)
  | .aggregate => (Ref .target .schema × Nat × List Graph.Value)
  | .region => (Ref .target .regionBinder × Option NodeId × List Graph.OwnedRef)
  | .regionScope => (Ref .target .block × NodeId × Option NodeId)
  | .injection => NodeId
  | .protection => (Ref .target .block × Graph.OwnedRef × Option NodeId × Option NodeId × Option NodeId × Option NodeId)
  | .cleanupReturn => (Graph.OwnedRef × Option NodeId × NodeId)
  | .disposalReturn => (Ref .target .schema × Option NodeId × List Graph.Value)
  | .unwind => (Option NodeId × List Graph.Value)
  | .cell => (Ref .target .schema × NodeId × Option Graph.Value)
  | .oneShot => Graph.Capture
  | .multiTemplate => Graph.Capture
  | .branch => (NodeId × NodeId × List (NodeId × NodeId))
  | .package => (Ref .target .schema × Graph.Value)
  | .computation => (Ref .target .constructor × NodeId)
  | .resource => (Ref .target .schema × Graph.Value)
  | .borrow => (Ref .target .schema × NodeId × NodeId)
  | .obligation => (Ref .target .block × Option Graph.Value × Option Graph.Value × Graph.ObligationStatus)
  | .pending => (Ref .target .effect × Graph.Value × NodeId × Ref .target .block)
  | .exit => Graph.Exit

def nodeView : Graph.Node → Sigma (nodePayload)
  | .control v0 => ⟨.control, v0⟩
  | .continuation v0 => ⟨.continuation, v0⟩
  | .handler v0 v1 v2 v3 => ⟨.handler, (v0, v1, v2, v3)⟩
  | .attachment v0 v1 v2 v3 v4 => ⟨.attachment, (v0, v1, v2, v3, v4)⟩
  | .environment v0 v1 => ⟨.environment, (v0, v1)⟩
  | .aggregate v0 v1 v2 => ⟨.aggregate, (v0, v1, v2)⟩
  | .region v0 v1 v2 => ⟨.region, (v0, v1, v2)⟩
  | .regionScope v0 v1 v2 => ⟨.regionScope, (v0, v1, v2)⟩
  | .injection v0 => ⟨.injection, v0⟩
  | .protection v0 v1 v2 v3 v4 v5 => ⟨.protection, (v0, v1, v2, v3, v4, v5)⟩
  | .cleanupReturn v0 v1 v2 => ⟨.cleanupReturn, (v0, v1, v2)⟩
  | .disposalReturn v0 v1 v2 => ⟨.disposalReturn, (v0, v1, v2)⟩
  | .unwind v0 v1 => ⟨.unwind, (v0, v1)⟩
  | .cell v0 v1 v2 => ⟨.cell, (v0, v1, v2)⟩
  | .oneShot v0 => ⟨.oneShot, v0⟩
  | .multiTemplate v0 => ⟨.multiTemplate, v0⟩
  | .branch v0 v1 v2 => ⟨.branch, (v0, v1, v2)⟩
  | .package v0 v1 => ⟨.package, (v0, v1)⟩
  | .computation v0 v1 => ⟨.computation, (v0, v1)⟩
  | .resource v0 v1 => ⟨.resource, (v0, v1)⟩
  | .borrow v0 v1 v2 => ⟨.borrow, (v0, v1, v2)⟩
  | .obligation v0 v1 v2 v3 => ⟨.obligation, (v0, v1, v2, v3)⟩
  | .pending v0 v1 v2 v3 => ⟨.pending, (v0, v1, v2, v3)⟩
  | .exit v0 => ⟨.exit, v0⟩

def nodeOfView : Sigma (nodePayload) → Graph.Node
  | ⟨.control, v0⟩ => .control v0
  | ⟨.continuation, v0⟩ => .continuation v0
  | ⟨.handler, (v0, v1, v2, v3)⟩ => .handler v0 v1 v2 v3
  | ⟨.attachment, (v0, v1, v2, v3, v4)⟩ => .attachment v0 v1 v2 v3 v4
  | ⟨.environment, (v0, v1)⟩ => .environment v0 v1
  | ⟨.aggregate, (v0, v1, v2)⟩ => .aggregate v0 v1 v2
  | ⟨.region, (v0, v1, v2)⟩ => .region v0 v1 v2
  | ⟨.regionScope, (v0, v1, v2)⟩ => .regionScope v0 v1 v2
  | ⟨.injection, v0⟩ => .injection v0
  | ⟨.protection, (v0, v1, v2, v3, v4, v5)⟩ => .protection v0 v1 v2 v3 v4 v5
  | ⟨.cleanupReturn, (v0, v1, v2)⟩ => .cleanupReturn v0 v1 v2
  | ⟨.disposalReturn, (v0, v1, v2)⟩ => .disposalReturn v0 v1 v2
  | ⟨.unwind, (v0, v1)⟩ => .unwind v0 v1
  | ⟨.cell, (v0, v1, v2)⟩ => .cell v0 v1 v2
  | ⟨.oneShot, v0⟩ => .oneShot v0
  | ⟨.multiTemplate, v0⟩ => .multiTemplate v0
  | ⟨.branch, (v0, v1, v2)⟩ => .branch v0 v1 v2
  | ⟨.package, (v0, v1)⟩ => .package v0 v1
  | ⟨.computation, (v0, v1)⟩ => .computation v0 v1
  | ⟨.resource, (v0, v1)⟩ => .resource v0 v1
  | ⟨.borrow, (v0, v1, v2)⟩ => .borrow v0 v1 v2
  | ⟨.obligation, (v0, v1, v2, v3)⟩ => .obligation v0 v1 v2 v3
  | ⟨.pending, (v0, v1, v2, v3)⟩ => .pending v0 v1 v2 v3
  | ⟨.exit, v0⟩ => .exit v0

def nodeFields : (tag : NodeTag) → Codec (nodePayload tag)
  | .control => (control).toCodec
  | .continuation => (continuation).toCodec
  | .handler => (((NonemptyCodec.reference .target .handler).pair (((value).list.pair (((NonemptyCodec.optional ((NonemptyCodec.reference .runtime .node)).toCodec).pair ((NonemptyCodec.optional ((NonemptyCodec.reference .runtime .node)).toCodec)).toCodec)).toCodec)).toCodec)).toCodec
  | .attachment => (((NonemptyCodec.reference .runtime .node).pair (((NonemptyCodec.optional ((NonemptyCodec.reference .runtime .node)).toCodec).pair (((NonemptyCodec.optional ((NonemptyCodec.reference .runtime .node)).toCodec).pair ((attachmentPhase.pair ((NonemptyCodec.optional ((NonemptyCodec.reference .runtime .node)).toCodec)).toCodec)).toCodec)).toCodec)).toCodec)).toCodec
  | .environment => (((value).list.pair ((NonemptyCodec.optional ((NonemptyCodec.reference .runtime .node)).toCodec)).toCodec)).toCodec
  | .aggregate => (((NonemptyCodec.reference .target .schema).pair ((NonemptyCodec.natural.pair ((value).list).toCodec)).toCodec)).toCodec
  | .region => (((NonemptyCodec.reference .target .regionBinder).pair (((NonemptyCodec.optional ((NonemptyCodec.reference .runtime .node)).toCodec).pair ((ownedRef).list).toCodec)).toCodec)).toCodec
  | .regionScope => (((NonemptyCodec.reference .target .block).pair (((NonemptyCodec.reference .runtime .node).pair ((NonemptyCodec.optional ((NonemptyCodec.reference .runtime .node)).toCodec)).toCodec)).toCodec)).toCodec
  | .injection => ((NonemptyCodec.reference .runtime .node)).toCodec
  | .protection => (((NonemptyCodec.reference .target .block).pair ((ownedRef.pair (((NonemptyCodec.optional ((NonemptyCodec.reference .runtime .node)).toCodec).pair (((NonemptyCodec.optional ((NonemptyCodec.reference .runtime .node)).toCodec).pair (((NonemptyCodec.optional ((NonemptyCodec.reference .runtime .node)).toCodec).pair ((NonemptyCodec.optional ((NonemptyCodec.reference .runtime .node)).toCodec)).toCodec)).toCodec)).toCodec)).toCodec)).toCodec)).toCodec
  | .cleanupReturn => ((ownedRef.pair (((NonemptyCodec.optional ((NonemptyCodec.reference .runtime .node)).toCodec).pair ((NonemptyCodec.reference .runtime .node)).toCodec)).toCodec)).toCodec
  | .disposalReturn => (((NonemptyCodec.reference .target .schema).pair (((NonemptyCodec.optional ((NonemptyCodec.reference .runtime .node)).toCodec).pair ((value).list).toCodec)).toCodec)).toCodec
  | .unwind => (((NonemptyCodec.optional ((NonemptyCodec.reference .runtime .node)).toCodec).pair ((value).list).toCodec)).toCodec
  | .cell => (((NonemptyCodec.reference .target .schema).pair (((NonemptyCodec.reference .runtime .node).pair ((NonemptyCodec.optional (value).toCodec)).toCodec)).toCodec)).toCodec
  | .oneShot => (captureState).toCodec
  | .multiTemplate => (captureState).toCodec
  | .branch => (((NonemptyCodec.reference .runtime .node).pair (((NonemptyCodec.reference .runtime .node).pair ((((NonemptyCodec.reference .runtime .node).pair ((NonemptyCodec.reference .runtime .node)).toCodec)).list).toCodec)).toCodec)).toCodec
  | .package => (((NonemptyCodec.reference .target .schema).pair (value).toCodec)).toCodec
  | .computation => (((NonemptyCodec.reference .target .constructor).pair ((NonemptyCodec.reference .runtime .node)).toCodec)).toCodec
  | .resource => (((NonemptyCodec.reference .target .schema).pair (value).toCodec)).toCodec
  | .borrow => (((NonemptyCodec.reference .target .schema).pair (((NonemptyCodec.reference .runtime .node).pair ((NonemptyCodec.reference .runtime .node)).toCodec)).toCodec)).toCodec
  | .obligation => (((NonemptyCodec.reference .target .block).pair (((NonemptyCodec.optional (value).toCodec).pair (((NonemptyCodec.optional (value).toCodec).pair (obligationStatus).toCodec)).toCodec)).toCodec)).toCodec
  | .pending => (((NonemptyCodec.reference .target .effect).pair ((value.pair (((NonemptyCodec.reference .runtime .node).pair ((NonemptyCodec.reference .target .block)).toCodec)).toCodec)).toCodec)).toCodec
  | .exit => (exit).toCodec

def node : NonemptyCodec (Graph.Node) :=
  (NonemptyCodec.dependent nodeTag (nodeFields)).iso
    (nodeOfView) (nodeView)
    (by intro value; cases value <;> rfl)
    (by rintro ⟨tag, data⟩; cases tag with
      | control => rfl
      | continuation => rfl
      | handler => rcases data with ⟨v0, v1, v2, v3⟩; rfl
      | attachment => rcases data with ⟨v0, v1, v2, v3, v4⟩; rfl
      | environment => rcases data with ⟨v0, v1⟩; rfl
      | aggregate => rcases data with ⟨v0, v1, v2⟩; rfl
      | region => rcases data with ⟨v0, v1, v2⟩; rfl
      | regionScope => rcases data with ⟨v0, v1, v2⟩; rfl
      | injection => rfl
      | protection => rcases data with ⟨v0, v1, v2, v3, v4, v5⟩; rfl
      | cleanupReturn => rcases data with ⟨v0, v1, v2⟩; rfl
      | disposalReturn => rcases data with ⟨v0, v1, v2⟩; rfl
      | unwind => rcases data with ⟨v0, v1⟩; rfl
      | cell => rcases data with ⟨v0, v1, v2⟩; rfl
      | oneShot => rfl
      | multiTemplate => rfl
      | branch => rcases data with ⟨v0, v1, v2⟩; rfl
      | package => rcases data with ⟨v0, v1⟩; rfl
      | computation => rcases data with ⟨v0, v1⟩; rfl
      | resource => rcases data with ⟨v0, v1⟩; rfl
      | borrow => rcases data with ⟨v0, v1, v2⟩; rfl
      | obligation => rcases data with ⟨v0, v1, v2, v3⟩; rfl
      | pending => rcases data with ⟨v0, v1, v2, v3⟩; rfl
      | exit => rfl
    )

def graphRoots : NonemptyCodec (Graph.Roots) :=
  ((NonemptyCodec.optional ((NonemptyCodec.reference .runtime .node)).toCodec).pair (((NonemptyCodec.optional ((NonemptyCodec.reference .runtime .node)).toCodec).pair (((ownedRef).list.pair (((NonemptyCodec.optional ((NonemptyCodec.reference .runtime .node)).toCodec).pair ((NonemptyCodec.optional ((NonemptyCodec.reference .runtime .node)).toCodec)).toCodec)).toCodec)).toCodec)).toCodec).iso
    (fun (v0, v1, v2, v3, v4) => { current := v0, evidence := v1, detached := v2, exit := v3, pending := v4 })
    (fun value => (value.current, value.evidence, value.detached, value.exit, value.pending))
    (by intro value; cases value; rfl)
    (by intro value; rcases value with ⟨v0, v1, v2, v3, v4⟩; rfl)

def graphStatusValues : List Graph.Status := [.active, .yielded, .parked, .unwinding]

def graphStatusName : Graph.Status → String
  | .active => "active"
  | .yielded => "yielded"
  | .parked => "parked"
  | .unwinding => "unwinding"

def graphStatus : NonemptyCodec Graph.Status :=
  NonemptyCodec.enumeration graphStatusValues
    (by intro value; cases value <;> simp [graphStatusValues]) (by decide) (by decide)

def rawState : NonemptyCodec (Graph.State) :=
  ((NonemptyCodec.fixedBytes 32 (by decide)).pair ((graphStatus.pair ((graphRoots.pair (((node).list.pair ((graphBlob).list).toCodec)).toCodec)).toCodec)).toCodec).iso
    (fun (v0, v1, v2, v3, v4) => { programIdentity := v0, status := v1, roots := v2, nodes := v3, blobs := v4 })
    (fun value => (value.programIdentity, value.status, value.roots, value.nodes, value.blobs))
    (by intro value; cases value; rfl)
    (by intro value; rcases value with ⟨v0, v1, v2, v3, v4⟩; rfl)

end BoundaryV2.Profile.Codecs
