const formal_core = @import("formal_core_registry");
const std = @import("std");
const witnesses = @import("witnesses");

const output_path = "FORMAL_CORE.md";
const registry_path = "src/formal_core_registry.zig";
const witness_path = "src/witnesses.zig";
const compile_fail_dir = "test/compile_fail/";
const examples_dir = "examples/";

fn usage() noreturn {
    std.debug.print("usage: zig build formal-core-write | zig build formal-core\n", .{});
    std.process.exit(1);
}

fn witnessExists(id: []const u8) bool {
    for (witnesses.witnesses) |witness| {
        if (std.mem.eql(u8, witness.witness_id, id)) return true;
    }
    return false;
}

fn validateRegistry() !void {
    inline for (formal_core.sections) |section| {
        _ = formal_core.anchorId(section.section_id);
        _ = formal_core.anchorPath(section.section_id);

        for (section.witness_ids) |witness_id| {
            if (!witnessExists(witness_id)) {
                std.debug.print("formal-core registry references missing witness id: {s}\n", .{witness_id});
                return error.UnknownWitnessId;
            }
            const mapped = formal_core.sectionForWitness(witness_id) orelse {
                std.debug.print("formal-core registry missing section mapping for witness id: {s}\n", .{witness_id});
                return error.MissingWitnessSectionMapping;
            };
            if (mapped != section.section_id) {
                std.debug.print("formal-core registry maps witness id {s} to the wrong section\n", .{witness_id});
                return error.WitnessSectionMismatch;
            }
        }

        for (section.example_ids) |example_id| {
            var buffer: [128]u8 = undefined;
            const example_path = try std.fmt.bufPrint(&buffer, examples_dir ++ "{s}.zig", .{example_id});
            std.fs.cwd().access(example_path, .{}) catch {
                std.debug.print("formal-core registry references missing example file: {s}\n", .{example_path});
                return error.UnknownExampleId;
            };
        }

        for (section.fixture_files) |fixture_file| {
            var buffer: [160]u8 = undefined;
            const fixture_path = try std.fmt.bufPrint(&buffer, compile_fail_dir ++ "{s}", .{fixture_file});
            std.fs.cwd().access(fixture_path, .{}) catch {
                std.debug.print("formal-core registry references missing compile-fail fixture: {s}\n", .{fixture_path});
                return error.UnknownFixtureFile;
            };
        }
    }
}

fn appendListLine(writer: anytype, label: []const u8, items: []const []const u8) !void {
    try writer.print("- {s}: ", .{label});
    for (items, 0..) |item, index| {
        if (index != 0) try writer.writeAll(", ");
        try writer.print("`{s}`", .{item});
    }
    try writer.writeByte('\n');
}

fn appendUnique(list: *std.ArrayList([]const u8), allocator: std.mem.Allocator, value: []const u8) !void {
    for (list.items) |existing| {
        if (std.mem.eql(u8, existing, value)) return;
    }
    try list.append(allocator, value);
}

fn render(allocator: std.mem.Allocator) ![]u8 {
    var output: std.ArrayList(u8) = .empty;
    errdefer output.deinit(allocator);
    var allocating: std.Io.Writer.Allocating = .fromArrayList(allocator, &output);
    const writer = &allocating.writer;

    try writer.writeAll(
        "# Formal Core\n\n" ++
            "<!-- generated by `zig build formal-core-write`; do not edit by hand -->\n\n" ++
            "This file is the small implementation-derived core for the current `shift`\n" ++
            "surface. It is generator-owned and checked by the build so the law surface\n" ++
            "cannot drift independently from the witness and contract registries. The public\n" ++
            "story is the root-level runtime kernel; witness ids, bridge ids, and frontend\n" ++
            "spellings remain proof-facing internal detail.\n",
    );

    inline for (formal_core.sections) |section| {
        try writer.writeByte('\n');
        try writer.print("<a id=\"{s}\"></a>\n", .{formal_core.anchorId(section.section_id)});
        try writer.print("## {s}\n\n", .{section.title});
        for (section.paragraphs, 0..) |paragraph, index| {
            if (index != 0) try writer.writeByte('\n');
            try writer.print("{s}\n", .{paragraph});
        }
    }

    var witness_ids: std.ArrayList([]const u8) = .empty;
    defer witness_ids.deinit(allocator);
    var example_ids: std.ArrayList([]const u8) = .empty;
    defer example_ids.deinit(allocator);
    var fixture_files: std.ArrayList([]const u8) = .empty;
    defer fixture_files.deinit(allocator);

    inline for (formal_core.sections) |section| {
        for (section.witness_ids) |witness_id| try appendUnique(&witness_ids, allocator, witness_id);
        for (section.example_ids) |example_id| try appendUnique(&example_ids, allocator, example_id);
        for (section.fixture_files) |fixture_file| try appendUnique(&fixture_files, allocator, fixture_file);
    }

    try writer.writeAll(
        "\n## Provenance\n\n" ++
            "Generated by `zig build formal-core-write` via `tools/render_formal_core.zig`.\n\n",
    );
    try appendListLine(writer, "registry", &.{registry_path});
    try appendListLine(writer, "witness_source", &.{witness_path});
    if (witness_ids.items.len != 0) try appendListLine(writer, "witness_ids", witness_ids.items);
    if (example_ids.items.len != 0) try appendListLine(writer, "example_ids", example_ids.items);
    if (fixture_files.items.len != 0) try appendListLine(writer, "compile_fail_fixtures", fixture_files.items);

    output = allocating.toArrayList();
    return try output.toOwnedSlice(allocator);
}

fn writeOutput(contents: []const u8) !void {
    var file = try std.fs.cwd().createFile(output_path, .{ .truncate = true });
    defer file.close();
    var buffer: [4096]u8 = undefined;
    var file_writer = file.writer(&buffer);
    const writer = &file_writer.interface;
    try writer.writeAll(contents);
    try writer.flush();
}

fn checkOutput(allocator: std.mem.Allocator, contents: []const u8) !void {
    const existing = try std.fs.cwd().readFileAlloc(allocator, output_path, 1 << 20);
    defer allocator.free(existing);
    if (!std.mem.eql(u8, existing, contents)) {
        std.debug.print("FORMAL_CORE.md is stale; run `zig build formal-core-write`\n", .{});
        return error.StaleFormalCore;
    }
}

/// Render or validate the generator-owned `FORMAL_CORE.md` artifact.
pub fn main() anyerror!void {
    var arena = std.heap.ArenaAllocator.init(std.heap.page_allocator);
    defer arena.deinit();
    const allocator = arena.allocator();

    var args = try std.process.argsWithAllocator(allocator);
    defer args.deinit();

    _ = args.next();
    const mode = args.next() orelse usage();
    if (args.next() != null) usage();

    try validateRegistry();
    const contents = try render(allocator);
    defer allocator.free(contents);

    if (std.mem.eql(u8, mode, "write")) {
        try writeOutput(contents);
        return;
    }
    if (std.mem.eql(u8, mode, "check")) {
        try checkOutput(allocator, contents);
        return;
    }

    usage();
}
