const formal_core = @import("formal_core_registry");

const canonical_note = "Canonical through the internal source-lowering toolchain with direct-source and canonical-scenario parity proof.";
const witness_canonical_note = "Canonical through the internal source-lowering witness source with direct-source, canonical-scenario, evaluator, reference-machine, and runtime parity proof.";

/// Coverage category for the steady-state source-lowering proof surface.
pub const Category = enum {
    built_in_effect,
    example,
    user_defined_effect,
    witness,
};

/// Current coverage state for one source-lowering row.
pub const CoverageStatus = enum {
    covered,
    gap,
};

/// One current public or proof-facing surface covered by the internal source-lowering track.
pub const Row = struct {
    coverage_id: []const u8,
    category: Category,
    current_surface: []const u8,
    current_signal: []const u8,
    law_anchor: []const u8,
    source_label: []const u8,
    coverage_status: CoverageStatus = .gap,
    note: []const u8,
};

/// Generator-owned source-lowering coverage registry.
pub const rows = [_]Row{
    .{
        .coverage_id = "witness.atm_resume_transform",
        .category = .witness,
        .current_surface = "witnesses.atm_resume_transform",
        .current_signal = "parity_scenarios:atm_resume_transform",
        .law_anchor = formal_core.anchorPath(.atm_resume_transform),
        .source_label = "source.witness.atm_resume_transform",
        .coverage_status = .covered,
        .note = witness_canonical_note,
    },
    .{
        .coverage_id = "witness.direct_return",
        .category = .witness,
        .current_surface = "witnesses.direct_return",
        .current_signal = "parity_scenarios:direct_return",
        .law_anchor = formal_core.anchorPath(.direct_return),
        .source_label = "source.witness.direct_return",
        .coverage_status = .covered,
        .note = witness_canonical_note,
    },
    .{
        .coverage_id = "witness.resume_or_return_return_now",
        .category = .witness,
        .current_surface = "witnesses.resume_or_return_return_now",
        .current_signal = "parity_scenarios:resume_or_return_return_now",
        .law_anchor = formal_core.anchorPath(.optional_resumption),
        .source_label = "source.witness.resume_or_return_return_now",
        .coverage_status = .covered,
        .note = witness_canonical_note,
    },
    .{
        .coverage_id = "witness.resume_or_return_resume",
        .category = .witness,
        .current_surface = "witnesses.resume_or_return_resume",
        .current_signal = "parity_scenarios:resume_or_return_resume",
        .law_anchor = formal_core.anchorPath(.optional_resumption),
        .source_label = "source.witness.resume_or_return_resume",
        .coverage_status = .covered,
        .note = witness_canonical_note,
    },
    .{
        .coverage_id = "witness.static_redelim",
        .category = .witness,
        .current_surface = "witnesses.static_redelim",
        .current_signal = "parity_scenarios:static_redelim",
        .law_anchor = formal_core.anchorPath(.static_redelim),
        .source_label = "source.witness.static_redelim",
        .coverage_status = .covered,
        .note = witness_canonical_note,
    },
    .{
        .coverage_id = "witness.multi_prompt",
        .category = .witness,
        .current_surface = "witnesses.multi_prompt",
        .current_signal = "parity_scenarios:multi_prompt",
        .law_anchor = formal_core.anchorPath(.multi_prompt_separation),
        .source_label = "source.witness.multi_prompt",
        .coverage_status = .covered,
        .note = witness_canonical_note,
    },
    .{
        .coverage_id = "witness.generator",
        .category = .witness,
        .current_surface = "witnesses.generator",
        .current_signal = "parity_scenarios:generator",
        .law_anchor = formal_core.anchorPath(.practical_witnesses),
        .source_label = "source.witness.generator",
        .coverage_status = .covered,
        .note = witness_canonical_note,
    },
    .{
        .coverage_id = "example.define_basic",
        .category = .example,
        .current_surface = "examples.define_basic",
        .current_signal = "example_proof:define_basic.txt",
        .law_anchor = formal_core.anchorPath(.strict_effect_capabilities),
        .source_label = "source.example.define_basic",
        .coverage_status = .covered,
        .note = canonical_note,
    },
    .{
        .coverage_id = "example.define_choice_basic",
        .category = .example,
        .current_surface = "examples.define_choice_basic",
        .current_signal = "example_proof:define_choice_basic.txt",
        .law_anchor = formal_core.anchorPath(.strict_effect_capabilities),
        .source_label = "source.example.define_choice_basic",
        .coverage_status = .covered,
        .note = canonical_note,
    },
    .{
        .coverage_id = "example.define_abort_basic",
        .category = .example,
        .current_surface = "examples.define_abort_basic",
        .current_signal = "example_proof:define_abort_basic.txt",
        .law_anchor = formal_core.anchorPath(.strict_effect_capabilities),
        .source_label = "source.example.define_abort_basic",
        .coverage_status = .covered,
        .note = canonical_note,
    },
    .{
        .coverage_id = "example.early_exit",
        .category = .example,
        .current_surface = "examples.early_exit",
        .current_signal = "example_proof:early_exit.txt",
        .law_anchor = formal_core.anchorPath(.direct_return),
        .source_label = "source.example.early_exit",
        .coverage_status = .covered,
        .note = canonical_note,
    },
    .{
        .coverage_id = "example.resume_or_return",
        .category = .example,
        .current_surface = "examples.resume_or_return",
        .current_signal = "example_proof:resume_or_return.txt",
        .law_anchor = formal_core.anchorPath(.optional_resumption),
        .source_label = "source.example.resume_or_return",
        .coverage_status = .covered,
        .note = canonical_note,
    },
    .{
        .coverage_id = "example.nested_workflow",
        .category = .example,
        .current_surface = "examples.nested_workflow",
        .current_signal = "example_proof:nested_workflow.txt",
        .law_anchor = formal_core.anchorPath(.practical_witnesses),
        .source_label = "source.example.nested_workflow",
        .coverage_status = .covered,
        .note = canonical_note,
    },
    .{
        .coverage_id = "example.exception_basic",
        .category = .example,
        .current_surface = "examples.exception_basic",
        .current_signal = "example_proof:exception_basic.txt",
        .law_anchor = formal_core.anchorPath(.exception_effect),
        .source_label = "source.example.exception_basic",
        .coverage_status = .covered,
        .note = canonical_note,
    },
    .{
        .coverage_id = "example.front_door_workflow",
        .category = .example,
        .current_surface = "examples.front_door_workflow",
        .current_signal = "example_proof:front_door_workflow.txt",
        .law_anchor = formal_core.anchorPath(.practical_witnesses),
        .source_label = "source.example.front_door_workflow",
        .coverage_status = .covered,
        .note = canonical_note,
    },
    .{
        .coverage_id = "example.optional_basic",
        .category = .example,
        .current_surface = "examples.optional_basic",
        .current_signal = "example_proof:optional_basic.txt",
        .law_anchor = formal_core.anchorPath(.optional_resumption),
        .source_label = "source.example.optional_basic",
        .coverage_status = .covered,
        .note = canonical_note,
    },
    .{
        .coverage_id = "example.reader_basic",
        .category = .example,
        .current_surface = "examples.reader_basic",
        .current_signal = "example_proof:reader_basic.txt",
        .law_anchor = formal_core.anchorPath(.strict_effect_capabilities),
        .source_label = "source.example.reader_basic",
        .coverage_status = .covered,
        .note = canonical_note,
    },
    .{
        .coverage_id = "example.resource_basic",
        .category = .example,
        .current_surface = "examples.resource_basic",
        .current_signal = "example_proof:resource_basic.txt",
        .law_anchor = formal_core.anchorPath(.resource_bracketing),
        .source_label = "source.example.resource_basic",
        .coverage_status = .covered,
        .note = canonical_note,
    },
    .{
        .coverage_id = "example.state_basic",
        .category = .example,
        .current_surface = "examples.state_basic",
        .current_signal = "example_proof:state_basic.txt",
        .law_anchor = formal_core.anchorPath(.strict_effect_capabilities),
        .source_label = "source.example.state_basic",
        .coverage_status = .covered,
        .note = canonical_note,
    },
    .{
        .coverage_id = "example.writer_basic",
        .category = .example,
        .current_surface = "examples.writer_basic",
        .current_signal = "example_proof:writer_basic.txt",
        .law_anchor = formal_core.anchorPath(.construction_coverage),
        .source_label = "source.example.writer_basic",
        .coverage_status = .covered,
        .note = canonical_note,
    },
    .{
        .coverage_id = "example.algebraic_abortive_validation",
        .category = .example,
        .current_surface = "examples.algebraic_abortive_validation",
        .current_signal = "example_proof:algebraic_abortive_validation.txt",
        .law_anchor = formal_core.anchorPath(.public_algebraic_builders),
        .source_label = "source.example.algebraic_abortive_validation",
        .coverage_status = .covered,
        .note = canonical_note,
    },
    .{
        .coverage_id = "example.algebraic_artifact_search",
        .category = .example,
        .current_surface = "examples.algebraic_artifact_search",
        .current_signal = "example_proof:algebraic_artifact_search.txt",
        .law_anchor = formal_core.anchorPath(.public_algebraic_builders),
        .source_label = "source.example.algebraic_artifact_search",
        .coverage_status = .covered,
        .note = canonical_note,
    },
    .{
        .coverage_id = "built_in.state",
        .category = .built_in_effect,
        .current_surface = "shift.Decl.state",
        .current_signal = "example_proof:state_basic.txt",
        .law_anchor = formal_core.anchorPath(.strict_effect_capabilities),
        .source_label = "source.effect.state",
        .coverage_status = .covered,
        .note = canonical_note,
    },
    .{
        .coverage_id = "built_in.reader",
        .category = .built_in_effect,
        .current_surface = "shift.Decl.reader",
        .current_signal = "example_proof:reader_basic.txt",
        .law_anchor = formal_core.anchorPath(.strict_effect_capabilities),
        .source_label = "source.effect.reader",
        .coverage_status = .covered,
        .note = canonical_note,
    },
    .{
        .coverage_id = "built_in.optional",
        .category = .built_in_effect,
        .current_surface = "shift.Decl.optional",
        .current_signal = "example_proof:optional_basic.txt",
        .law_anchor = formal_core.anchorPath(.optional_resumption),
        .source_label = "source.effect.optional",
        .coverage_status = .covered,
        .note = canonical_note,
    },
    .{
        .coverage_id = "built_in.exception",
        .category = .built_in_effect,
        .current_surface = "shift.Decl.exception",
        .current_signal = "example_proof:exception_basic.txt",
        .law_anchor = formal_core.anchorPath(.exception_effect),
        .source_label = "source.effect.exception",
        .coverage_status = .covered,
        .note = canonical_note,
    },
    .{
        .coverage_id = "built_in.resource",
        .category = .built_in_effect,
        .current_surface = "shift.Decl.resource",
        .current_signal = "example_proof:resource_basic.txt",
        .law_anchor = formal_core.anchorPath(.resource_bracketing),
        .source_label = "source.effect.resource",
        .coverage_status = .covered,
        .note = canonical_note,
    },
    .{
        .coverage_id = "built_in.writer",
        .category = .built_in_effect,
        .current_surface = "shift.Decl.writer",
        .current_signal = "example_proof:writer_basic.txt",
        .law_anchor = formal_core.anchorPath(.construction_coverage),
        .source_label = "source.effect.writer",
        .coverage_status = .covered,
        .note = canonical_note,
    },
    .{
        .coverage_id = "user_defined.transform",
        .category = .user_defined_effect,
        .current_surface = "shift.Decl.family.transform",
        .current_signal = "example_proof:define_basic.txt",
        .law_anchor = formal_core.anchorPath(.strict_effect_capabilities),
        .source_label = "source.user_defined.transform",
        .coverage_status = .covered,
        .note = canonical_note,
    },
    .{
        .coverage_id = "user_defined.choice",
        .category = .user_defined_effect,
        .current_surface = "shift.Decl.family.choice",
        .current_signal = "example_proof:define_choice_basic.txt",
        .law_anchor = formal_core.anchorPath(.strict_effect_capabilities),
        .source_label = "source.user_defined.choice",
        .coverage_status = .covered,
        .note = canonical_note,
    },
    .{
        .coverage_id = "user_defined.abort",
        .category = .user_defined_effect,
        .current_surface = "shift.Decl.family.abort",
        .current_signal = "example_proof:define_abort_basic.txt",
        .law_anchor = formal_core.anchorPath(.strict_effect_capabilities),
        .source_label = "source.user_defined.abort",
        .coverage_status = .covered,
        .note = canonical_note,
    },
};
