const formal_core = @import("formal_core_registry");

const planned_note = "Tracked by the ordinary-body cutover ledger, but not yet promoted through the public experimental ordinary-Zig lowering surface.";
const promoted_note = "Promoted through the public experimental ordinary-Zig lowering surface with direct-source and canonical-scenario parity proof.";

/// Replacement-row category for the long-horizon canonical ordinary-body campaign.
pub const Category = enum {
    built_in_effect,
    example,
    user_defined_effect,
    witness,
};

/// Current progress for one replacement row.
pub const Status = enum {
    candidate_green,
    canonical,
    parity_green,
    planned,
};

/// One current public or proof-facing surface that must eventually be replaced by the canonical ordinary-body path.
pub const Row = struct {
    replacement_id: []const u8,
    category: Category,
    current_surface: []const u8,
    current_signal: []const u8,
    law_anchor: []const u8,
    ordinary_target: []const u8,
    status: Status = .planned,
    note: []const u8,
};

/// Generator-owned long-horizon replacement ledger.
pub const rows = [_]Row{
    .{
        .replacement_id = "witness.atm_resume_transform",
        .category = .witness,
        .current_surface = "witnesses.atm_resume_transform",
        .current_signal = "parity_scenarios:atm_resume_transform",
        .law_anchor = formal_core.anchorPath(.atm_resume_transform),
        .ordinary_target = "ordinary.witness.atm_resume_transform",
        .status = .planned,
        .note = planned_note,
    },
    .{
        .replacement_id = "witness.direct_return",
        .category = .witness,
        .current_surface = "witnesses.direct_return",
        .current_signal = "parity_scenarios:direct_return",
        .law_anchor = formal_core.anchorPath(.direct_return),
        .ordinary_target = "ordinary.witness.direct_return",
        .status = .planned,
        .note = planned_note,
    },
    .{
        .replacement_id = "witness.resume_or_return_return_now",
        .category = .witness,
        .current_surface = "witnesses.resume_or_return_return_now",
        .current_signal = "parity_scenarios:resume_or_return_return_now",
        .law_anchor = formal_core.anchorPath(.optional_resumption),
        .ordinary_target = "ordinary.witness.resume_or_return_return_now",
        .status = .planned,
        .note = planned_note,
    },
    .{
        .replacement_id = "witness.resume_or_return_resume",
        .category = .witness,
        .current_surface = "witnesses.resume_or_return_resume",
        .current_signal = "parity_scenarios:resume_or_return_resume",
        .law_anchor = formal_core.anchorPath(.optional_resumption),
        .ordinary_target = "ordinary.witness.resume_or_return_resume",
        .status = .planned,
        .note = planned_note,
    },
    .{
        .replacement_id = "witness.static_redelim",
        .category = .witness,
        .current_surface = "witnesses.static_redelim",
        .current_signal = "parity_scenarios:static_redelim",
        .law_anchor = formal_core.anchorPath(.static_redelim),
        .ordinary_target = "ordinary.witness.static_redelim",
        .status = .planned,
        .note = planned_note,
    },
    .{
        .replacement_id = "witness.multi_prompt",
        .category = .witness,
        .current_surface = "witnesses.multi_prompt",
        .current_signal = "parity_scenarios:multi_prompt",
        .law_anchor = formal_core.anchorPath(.multi_prompt_separation),
        .ordinary_target = "ordinary.witness.multi_prompt",
        .status = .planned,
        .note = planned_note,
    },
    .{
        .replacement_id = "witness.generator",
        .category = .witness,
        .current_surface = "witnesses.generator",
        .current_signal = "parity_scenarios:generator",
        .law_anchor = formal_core.anchorPath(.practical_witnesses),
        .ordinary_target = "ordinary.witness.generator",
        .status = .planned,
        .note = planned_note,
    },
    .{
        .replacement_id = "example.define_basic",
        .category = .example,
        .current_surface = "examples.define_basic",
        .current_signal = "example_proof:define_basic.txt",
        .law_anchor = formal_core.anchorPath(.strict_effect_capabilities),
        .ordinary_target = "ordinary.example.define_basic",
        .status = .planned,
        .note = planned_note,
    },
    .{
        .replacement_id = "example.early_exit",
        .category = .example,
        .current_surface = "examples.early_exit",
        .current_signal = "example_proof:early_exit.txt",
        .law_anchor = formal_core.anchorPath(.direct_return),
        .ordinary_target = "ordinary.example.early_exit",
        .status = .parity_green,
        .note = promoted_note,
    },
    .{
        .replacement_id = "example.resume_or_return",
        .category = .example,
        .current_surface = "examples.resume_or_return",
        .current_signal = "example_proof:resume_or_return.txt",
        .law_anchor = formal_core.anchorPath(.optional_resumption),
        .ordinary_target = "ordinary.example.resume_or_return",
        .status = .parity_green,
        .note = promoted_note,
    },
    .{
        .replacement_id = "example.nested_workflow",
        .category = .example,
        .current_surface = "examples.nested_workflow",
        .current_signal = "example_proof:nested_workflow.txt",
        .law_anchor = formal_core.anchorPath(.practical_witnesses),
        .ordinary_target = "ordinary.example.nested_workflow",
        .status = .parity_green,
        .note = promoted_note,
    },
    .{
        .replacement_id = "example.exception_basic",
        .category = .example,
        .current_surface = "examples.exception_basic",
        .current_signal = "example_proof:exception_basic.txt",
        .law_anchor = formal_core.anchorPath(.exception_effect),
        .ordinary_target = "ordinary.example.exception_basic",
        .status = .parity_green,
        .note = promoted_note,
    },
    .{
        .replacement_id = "example.optional_basic",
        .category = .example,
        .current_surface = "examples.optional_basic",
        .current_signal = "example_proof:optional_basic.txt",
        .law_anchor = formal_core.anchorPath(.optional_resumption),
        .ordinary_target = "ordinary.example.optional_basic",
        .status = .parity_green,
        .note = promoted_note,
    },
    .{
        .replacement_id = "example.reader_basic",
        .category = .example,
        .current_surface = "examples.reader_basic",
        .current_signal = "example_proof:reader_basic.txt",
        .law_anchor = formal_core.anchorPath(.strict_effect_capabilities),
        .ordinary_target = "ordinary.example.reader_basic",
        .status = .parity_green,
        .note = promoted_note,
    },
    .{
        .replacement_id = "example.resource_basic",
        .category = .example,
        .current_surface = "examples.resource_basic",
        .current_signal = "example_proof:resource_basic.txt",
        .law_anchor = formal_core.anchorPath(.resource_bracketing),
        .ordinary_target = "ordinary.example.resource_basic",
        .status = .planned,
        .note = planned_note,
    },
    .{
        .replacement_id = "example.state_basic",
        .category = .example,
        .current_surface = "examples.state_basic",
        .current_signal = "example_proof:state_basic.txt",
        .law_anchor = formal_core.anchorPath(.strict_effect_capabilities),
        .ordinary_target = "ordinary.example.state_basic",
        .status = .parity_green,
        .note = promoted_note,
    },
    .{
        .replacement_id = "example.writer_basic",
        .category = .example,
        .current_surface = "examples.writer_basic",
        .current_signal = "example_proof:writer_basic.txt",
        .law_anchor = formal_core.anchorPath(.construction_coverage),
        .ordinary_target = "ordinary.example.writer_basic",
        .status = .planned,
        .note = planned_note,
    },
    .{
        .replacement_id = "example.algebraic_abortive_validation",
        .category = .example,
        .current_surface = "examples.algebraic_abortive_validation",
        .current_signal = "example_proof:algebraic_abortive_validation.txt",
        .law_anchor = formal_core.anchorPath(.public_algebraic_builders),
        .ordinary_target = "ordinary.example.algebraic_abortive_validation",
        .status = .planned,
        .note = planned_note,
    },
    .{
        .replacement_id = "example.algebraic_artifact_search",
        .category = .example,
        .current_surface = "examples.algebraic_artifact_search",
        .current_signal = "example_proof:algebraic_artifact_search.txt",
        .law_anchor = formal_core.anchorPath(.public_algebraic_builders),
        .ordinary_target = "ordinary.example.algebraic_artifact_search",
        .status = .planned,
        .note = planned_note,
    },
    .{
        .replacement_id = "built_in.state",
        .category = .built_in_effect,
        .current_surface = "shift.effect.state",
        .current_signal = "example_proof:state_basic.txt",
        .law_anchor = formal_core.anchorPath(.strict_effect_capabilities),
        .ordinary_target = "ordinary.effect.state",
        .status = .parity_green,
        .note = promoted_note,
    },
    .{
        .replacement_id = "built_in.reader",
        .category = .built_in_effect,
        .current_surface = "shift.effect.reader",
        .current_signal = "example_proof:reader_basic.txt",
        .law_anchor = formal_core.anchorPath(.strict_effect_capabilities),
        .ordinary_target = "ordinary.effect.reader",
        .status = .parity_green,
        .note = promoted_note,
    },
    .{
        .replacement_id = "built_in.optional",
        .category = .built_in_effect,
        .current_surface = "shift.effect.optional",
        .current_signal = "example_proof:optional_basic.txt",
        .law_anchor = formal_core.anchorPath(.optional_resumption),
        .ordinary_target = "ordinary.effect.optional",
        .status = .parity_green,
        .note = promoted_note,
    },
    .{
        .replacement_id = "built_in.exception",
        .category = .built_in_effect,
        .current_surface = "shift.effect.exception",
        .current_signal = "example_proof:exception_basic.txt",
        .law_anchor = formal_core.anchorPath(.exception_effect),
        .ordinary_target = "ordinary.effect.exception",
        .status = .parity_green,
        .note = promoted_note,
    },
    .{
        .replacement_id = "built_in.resource",
        .category = .built_in_effect,
        .current_surface = "shift.effect.resource",
        .current_signal = "example_proof:resource_basic.txt",
        .law_anchor = formal_core.anchorPath(.resource_bracketing),
        .ordinary_target = "ordinary.effect.resource",
        .status = .planned,
        .note = planned_note,
    },
    .{
        .replacement_id = "built_in.writer",
        .category = .built_in_effect,
        .current_surface = "shift.effect.writer",
        .current_signal = "example_proof:writer_basic.txt",
        .law_anchor = formal_core.anchorPath(.construction_coverage),
        .ordinary_target = "ordinary.effect.writer",
        .status = .planned,
        .note = planned_note,
    },
    .{
        .replacement_id = "user_defined.transform",
        .category = .user_defined_effect,
        .current_surface = "shift.effect.Define.transform",
        .current_signal = "example_proof:define_basic.txt",
        .law_anchor = formal_core.anchorPath(.strict_effect_capabilities),
        .ordinary_target = "ordinary.user_defined.transform",
        .status = .planned,
        .note = planned_note,
    },
    .{
        .replacement_id = "user_defined.choice",
        .category = .user_defined_effect,
        .current_surface = "shift.effect.Define.choice",
        .current_signal = "example_proof:define_choice_basic.txt",
        .law_anchor = formal_core.anchorPath(.strict_effect_capabilities),
        .ordinary_target = "ordinary.user_defined.choice",
        .status = .planned,
        .note = planned_note,
    },
    .{
        .replacement_id = "user_defined.abort",
        .category = .user_defined_effect,
        .current_surface = "shift.effect.Define.abort",
        .current_signal = "example_proof:define_abort_basic.txt",
        .law_anchor = formal_core.anchorPath(.strict_effect_capabilities),
        .ordinary_target = "ordinary.user_defined.abort",
        .status = .planned,
        .note = planned_note,
    },
};
